<?php defined('BASEPATH') OR exit('No direct script access allowed');

return [
    '表单可以用于前端数据展示与收集，如留言板、反馈、证书展示，需要配合前端页面使用' => 'Forms can be used for front-end data display and collection, such as message boards, feedback, and certificate display, and need to be used in conjunction with front-end pages',
    '已审核内容' => 'Approved content',
    '网站表单' => 'Website Form',
    '全局网站表单' => 'Website Form',
    '待审核内容' => 'Pending review content',
    '表单别名' => 'Form alias',
    '重建表单' => 'Rebuilding Form',
    '表单名称不能为空' => 'The form name cannot be empty',
    '数据表名称不能为空' => 'The data table name cannot be empty',
    '数据表名称格式不正确' => 'The format of the data table name is incorrect',
    '后台显示' => 'Backend display',
    '前端SEO设置' => 'Front end SEO settings',
    '发布权限设置' => 'Publishing permission settings',
    '前端权限' => 'Front end permissions',
    '公共表单' => 'Public Form',
    '私有表单' => 'Private Form',
    '私有表单不允许前端访问表单列表和查看表单内容' => 'Private forms do not allow front-end access to form lists and viewing form content',
    '权限划分' => 'Authority division',
    '发表' => 'publish',
    '内容SEO标题' => 'Content SEO Title',
    '内容SEO关键字' => 'Content SEO keywords',
    '内容SEO描述信息' => 'Content SEO Description Information',
    '用户管理内容' => 'User management content',
    '用户中心的内容管理菜单下可以管理自己提交的内容' => 'Under the content management menu in the user center, you can manage the content you submit',
    '表单名称' => 'Form Name',
    '表单的描述名称' => 'The description name of the form',
    '开发模式' => 'Development mode',
    '系统默认' => 'System default',
    '自定义模式时本表单不会自动生成到菜单之中，需要开发者手动写入菜单' => 'When in custom mode, this form will not be automatically generated into the menu and developers need to manually write it into the menu',
    '提交成功提示文字' => 'Submission success prompt text',
    '当用户提交表单成功之后显示的文字，默认为：操作成功' => 'The default text displayed after the user successfully submits the form is: Operation successful',
    '提交审核提示文字' => 'Submit review prompt text',
    '当用户提交表单审核时显示的文字，默认为：操作成功，等待管理员审核' => 'The default text displayed when a user submits a form for review is: Operation successful, waiting for administrator review',
    '提交成功跳转URL' => 'Successfully submitted to redirect URL',
    '当用户提交表单成功之后跳转的链接，{id}表示当前表单的id号' => 'After the user successfully submits the form, the link that redirects to {id} represents the ID number of the current form',
    '作者' => 'author',
    '通知模式' => 'Notification Mode',
    '队列模式' => 'Queue mode',
    '立即发送在提交时会带来卡顿现象，推荐使用队列模式' => 'Sending immediately may cause lag during submission, it is recommended to use queue mode',
    '通知方式' => 'Notification method',
    '邮件模式' => 'Email mode',
    '更多模式' => 'More modes',
    '通知邮箱' => 'Notification email',
    '直接填写邮箱地址，支持多个邮箱' => 'Directly fill in email address, supports multiple email addresses',
    '邮箱模板' => 'Email Template',
    '设置教程' => 'Set Up Tutorial',
    '通知账号' => 'Notify account',
    '当有人提交表单时，会通知到这些账号' => 'When someone submits a form, these accounts will be notified',
    '无法使用' => 'unavailable',
    '共（%s）个系统表单，重建文件（%s）个' => 'Total (%s) system forms, reconstructed files (%s)',
    '表单别名只能由字母或者字母+数字组成' => 'The form alias can only consist of letters or a combination of letters and numbers',
    '本功能需要安装【用户系统】插件' => 'This feature requires the installation of the <User System> plugin',


];