import type { IntentLandingConfig } from './intentLandingPages';

const authorizedResponse =
  'The platform escalates the confirmed event to the responsible team, supports the site\'s approved procedure, and preserves the decision and outcome for review.';

export const droneDefenderLanding: IntentLandingConfig = {
  handle: 'drone-defender',
  eyebrow: 'LAYERED DRONE DEFENDER',
  h1: 'Drone Defender for Layered Site Protection',
  purpose:
    'Combine RF detection, radar tracking, EO/IR confirmation and directional or omni-directional RF jammers in one layered site-protection workflow.',
  heroImage: '/solutions/low-altitude-airspace-monitoring/ntet-radar-back-side-facing-viewer-front-to-drone.webp',
  heroImageAlt: 'Layered Drone Defender configuration with radar and multi-sensor site monitoring',
  heroFacts: ['RF, radar and EO/IR detection', 'Directional and omni RF jammers', 'Authorized countermeasure workflow'],
  applicationHeading: 'What does a layered Drone Defender configuration include?',
  answerBlock:
    'A layered Drone Defender configuration combines detection, confirmation and an authorized countermeasure layer. Fixed RF detection provides signal awareness, supported identification and direction clues. Low-altitude radar adds range, bearing and continuous tracks, while EO/IR gives the operator visible and thermal confirmation. After the event is identified and confirmed, an authorized project may add a directional RF jammer for a reviewed sector or an omni-directional RF jammer for approved area coverage. These devices are not substitutes for detection: they sit downstream of sensor evidence, operator judgement and legal authority. Final design depends on the protected boundary, approach sectors, buildings, terrain, RF conditions, mounting positions, nearby communications, staffing and local rules. Published ranges remain reference conditions rather than guaranteed site coverage.',
  applications: [
    { title: 'Airport & transport boundaries', summary: 'Plan sector coverage, permitted-flight review and command-room handoff around operational zones.' },
    { title: 'Energy & industrial sites', summary: 'Combine perimeter awareness with traceable alert review around production and logistics areas.' },
    { title: 'Major venues & events', summary: 'Deploy time-bound monitoring with field-team coordination and a defined escalation path.' },
    { title: 'Government & managed sites', summary: 'Correlate identity, track and visual evidence before the responsible team makes a decision.' },
  ],
  productsHeading: 'Detection, confirmation and RF jammer layers',
  productsIntro: 'Build the evidence chain first, then select the authorized jammer geometry required by the protected site.',
  products: [
    {
      name: 'Stationary RF Identification System',
      summary: 'A fixed passive RF layer for signal awareness, supported identification, direction review and event handoff.',
      image: '/products/02-drone-detection/stationary-rf-detection-system.webp',
      imageAlt: 'Stationary RF identification system for layered drone protection',
      href: '/products/stationary-rf-detection-system',
      facts: ['Fixed-site passive RF sensing', '360-degree horizontal coverage', 'Identification and direction support'],
    },
    {
      name: 'Low-Altitude Early-Warning Radar',
      summary: 'A movement-tracking layer for early warning, trajectory review and cueing other sensors.',
      image: '/products/02-drone-detection/low-altitude-detection-radar.webp',
      imageAlt: 'Low-altitude radar for Drone Defender tracking',
      href: '/products/low-altitude-detection-radar-ku-band',
      facts: ['Range and bearing evidence', '360-degree azimuth coverage', 'Track data for platform handoff'],
    },
    {
      name: 'Electro-Optical Tracking System',
      summary: 'Visible-light and thermal imaging for operator confirmation, tracking and video evidence.',
      image: '/products/02-drone-detection/electro-optical-tracking-system.webp',
      imageAlt: 'Electro-optical and thermal tracking system for visual confirmation',
      href: '/products/composite-electro-optical-tracking-system',
      facts: ['Visible and thermal channels', 'Precision pan-tilt control', 'Radar cueing support'],
    },
    {
      name: 'Directional RF Jammer',
      summary: 'A directional RF suppression layer for an authorized, reviewed approach sector.',
      image: '/products/rf-systems/directional-rf-unit.webp',
      imageAlt: 'Directional RF Jammer for a reviewed protection sector',
      href: '/products/directional-rf-interference-device',
      facts: ['Directional sector geometry', 'Fixed-site platform integration', 'Authorization and EMC review required'],
    },
    {
      name: 'Omni-directional RF Jammer',
      summary: 'An omni-directional RF suppression layer for an approved fixed-site coverage area.',
      image: '/products/rf-systems/omni-directional-rf-unit.webp',
      imageAlt: 'Omni-directional RF Jammer for approved area coverage',
      href: '/products/omni-directional-rf-interference-device',
      facts: ['360-degree area geometry', 'Fixed-site platform integration', 'Authorization and EMC review required'],
    },
  ],
  comparisonHeading: 'Which protection layer closes which gap?',
  comparisonIntro: 'Compare evidence, site role and operating limits before selecting equipment.',
  comparisonColumns: ['RF detection', 'Radar', 'EO / IR', 'Directional jammer', 'Omni jammer'],
  comparisonRows: [
    { label: 'Primary role', values: ['Signal awareness, identity and direction clues', 'Movement, range, bearing and track', 'Visual and thermal confirmation', 'Sector-focused RF suppression', 'Approved-area RF suppression'] },
    { label: 'Workflow stage', values: ['Detection and identification', 'Detection and tracking', 'Confirmation', 'Authorized countermeasure', 'Authorized countermeasure'] },
    { label: 'Important limit', values: ['RF noise, unfamiliar waveforms and quiet targets', 'Clutter, terrain, mounting and target characteristics', 'Line of sight, weather and target presentation', 'Authority, sector geometry, EMC and nearby communications', 'Authority, area geometry, EMC and nearby communications'] },
    { label: 'Typical format', values: ['Fixed-site passive sensor', 'Fixed or vehicle-supported sensor', 'Fixed confirmation layer', 'Fixed directional unit', 'Fixed omni-directional unit'] },
  ],
  workflowHeading: 'From detection to an authorized countermeasure',
  workflowIntro: 'RF, radar and EO/IR build the evidence chain before a responsible operator can authorize an RF jammer response.',
  workflow: [
    { title: 'Detection', summary: 'RF and radar create an observation with time, signal, range, bearing and available track data.' },
    { title: 'Identification', summary: 'The platform compares RF clues, movement, map context and permitted-flight information while preserving uncertainty.' },
    { title: 'Confirmation', summary: 'EO/IR cueing and operator review add visual context, status and notes before escalation.' },
    { title: 'Authorized Countermeasure', summary: 'Where legally permitted, the responsible operator may select a directional or omni-directional RF jammer under the approved site procedure; the decision and outcome are recorded.' },
  ],
  scenariosHeading: 'Two drone defender scenarios',
  scenariosIntro: 'The protection workflow stays consistent while sensor placement and handoff rules change by site.',
  scenarios: [
    {
      title: 'Airport Boundary Protection',
      summary: 'Fixed RF, radar and EO/IR layers review approach sectors before an authorized directional or omni-directional jammer decision.',
      image: '/cases/airport-security-application/main-home.webp',
      imageAlt: 'Airport boundary drone defender solution scenario',
      href: '/cases/airport-security-application',
      points: ['Sector and blind-zone review', 'RF, radar and visual correlation', 'Authority check before RF suppression'],
    },
    {
      title: 'Industrial Perimeter Protection',
      summary: 'A continuous monitoring layout supports production areas, logistics routes and key perimeter sectors.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Industrial perimeter drone defender solution scenario',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Fixed RF, radar and EO/IR awareness', 'Confirmed target and responsible operator', 'Approved jammer geometry and event record'],
    },
  ],
  faqHeading: 'Drone Defender FAQ',
  faqs: [
    { question: 'Is Drone Defender one device?', answer: 'No. A complete configuration normally combines RF detection, radar tracking, EO/IR confirmation, a command platform and, where authorized, directional or omni-directional RF jammers.' },
    { question: 'Can one configuration protect every site?', answer: 'No. Boundaries, approach sectors, terrain, buildings, RF conditions, mounting and operator procedures change the useful design.' },
    { question: 'What happens after a target is confirmed?', answer: 'The platform hands the confirmed event to the responsible operator. Where legally authorized, the approved procedure may include a directional or omni-directional RF jammer response.' },
    { question: 'What is needed for a proposal?', answer: 'Provide a site map, protected sectors, permitted flights, operating hours, mounting options, power and network limits, operator roles and response authority.' },
  ],
  ctaLabel: 'Request Protection Plan',
};

export const droneLocatorLanding: IntentLandingConfig = {
  handle: 'drone-locator',
  eyebrow: 'MOBILE & FIXED DRONE LOCATION',
  h1: 'Drone Locator for Mobile & Fixed-Site Positioning',
  purpose:
    'Compare two mobile RF detection-and-location options with fixed RF, radar and EO/IR layers, then connect confirmed targets to an authorized jammer response.',
  heroImage: '/products/02-drone-detection/portable-rf-detection-case.webp',
  heroImageAlt: 'Portable RF drone detection and location equipment for mobile deployment',
  heroFacts: ['Two mobile RF options', 'Fixed RF, radar and EO/IR', 'Authorized jammer response'],
  applicationHeading: 'What does a site drone locator need to show?',
  answerBlock:
    'A drone locator project can begin with mobile equipment or a fixed sensor layout. The PL280H gives an individual patrol user lightweight RF alerts, while the Portable RF Identification System adds a larger display, identification and positioning support for a temporary post. Fixed sites can combine stationary RF detection with radar range, bearing and track data, then use EO/IR for visual confirmation. These sources should be correlated by time and map position rather than treated as interchangeable. Detection and location are not the final step: after identification and confirmation, an authorized project may hand the event to a Directional RF Jammer for a reviewed sector or an Omni-directional RF Jammer for approved area coverage. Buildings, terrain, RF noise, radar clutter, line of sight, mounting and legal authority all affect the final configuration.',
  applications: [
    { title: 'Individual mobile patrol', summary: 'Use the PL280H for lightweight local RF alerts while one operator is moving.' },
    { title: 'Temporary location post', summary: 'Use the portable RF case for identification, direction and position review with a larger display.' },
    { title: 'Fixed perimeter location', summary: 'Combine stationary RF, radar tracks and EO/IR confirmation around planned sectors.' },
    { title: 'Authorized countermeasure', summary: 'Pass a confirmed event to the approved directional or omni-directional RF jammer workflow.' },
  ],
  productsHeading: 'Mobile locators, fixed sensors and jammer options',
  productsIntro: 'Start with the two mobile location formats, add fixed RF, radar and EO/IR where continuity is required, then define the authorized countermeasure.',
  products: [
    {
      name: 'PL280H Handheld RF Detection System',
      summary: 'A lightweight passive RF detector for individual patrol, local alerts and rapid movement between sectors.',
      image: '/products/02-drone-detection/handheld-rf-detection-system-pl280h.webp',
      imageAlt: 'PL280H handheld RF drone detector for mobile patrol',
      href: '/products/handheld-rf-detection-system-mini',
      facts: ['Handheld patrol format', 'Passive RF monitoring', 'Visual, audible and vibration alerts'],
    },
    {
      name: 'Portable RF Identification System',
      summary: 'A hand-carried RF system with integrated display for identification, direction and positioning support at temporary posts.',
      image: '/products/02-drone-detection/portable-rf-detection-case.webp',
      imageAlt: 'Portable RF identification and drone location system',
      href: '/products/portable-rf-detection-case',
      facts: ['Hand-carried field case', 'Identification and positioning support', 'Integrated 13.3-inch display'],
    },
    {
      name: 'Stationary RF Identification System',
      summary: 'Fixed passive RF sensing for supported identification, direction finding and mapped event review.',
      image: '/products/02-drone-detection/stationary-rf-detection-system.webp',
      imageAlt: 'Stationary RF identification and direction-finding system',
      href: '/products/stationary-rf-detection-system',
      facts: ['Passive RF awareness', 'Direction-finding support', 'Fixed-site event handoff'],
    },
    {
      name: 'Low-Altitude Early-Warning Radar',
      summary: 'Provides movement, range, bearing and track data for non-cooperative target positioning.',
      image: '/products/02-drone-detection/low-altitude-detection-radar.webp',
      imageAlt: 'Low-altitude radar for drone track positioning',
      href: '/products/low-altitude-detection-radar-ku-band',
      facts: ['Range and bearing', 'Trajectory tracking', 'Multi-sensor cueing'],
    },
    {
      name: 'Electro-Optical Tracking System',
      summary: 'Adds visible and thermal imagery for operator confirmation and target tracking.',
      image: '/products/02-drone-detection/electro-optical-tracking-system.webp',
      imageAlt: 'Electro-optical system confirming a located drone target',
      href: '/products/composite-electro-optical-tracking-system',
      facts: ['Visible and thermal channels', 'Precision pan-tilt tracking', 'Radar linkage support'],
    },
    {
      name: 'Directional RF Jammer',
      summary: 'A directional RF suppression option for a confirmed target in a reviewed sector.',
      image: '/products/rf-systems/directional-rf-unit.webp',
      imageAlt: 'Directional RF Jammer for an authorized target sector',
      href: '/products/directional-rf-interference-device',
      facts: ['Directional countermeasure geometry', 'Fixed-site integration', 'Authority and safety review required'],
    },
    {
      name: 'Omni-directional RF Jammer',
      summary: 'An omni-directional RF suppression option for an approved fixed-site coverage area.',
      image: '/products/rf-systems/omni-directional-rf-unit.webp',
      imageAlt: 'Omni-directional RF Jammer for authorized area coverage',
      href: '/products/omni-directional-rf-interference-device',
      facts: ['360-degree countermeasure geometry', 'Fixed-site integration', 'Authority and safety review required'],
    },
  ],
  comparisonHeading: 'Which mobile, fixed or jammer layer fits the task?',
  comparisonIntro: 'Compare operator mobility, location evidence, confirmation and response authority—not range alone.',
  comparisonColumns: ['Handheld RF', 'Portable RF case', 'Fixed RF + radar', 'EO / IR', 'RF jammer'],
  comparisonRows: [
    { label: 'Best role', values: ['Individual mobile alerting', 'Temporary identification and location post', 'Continuous bearing and track coverage', 'Visual confirmation', 'Authorized countermeasure'] },
    { label: 'Primary output', values: ['Local RF alert', 'RF identity, direction and position clues', 'RF clues plus radar range, bearing and track', 'Visible and thermal imagery', 'Directional or area RF suppression'] },
    { label: 'Deployment', values: ['Handheld patrol', 'Hand-carried field case', 'Installed site sensors', 'Fixed cueing system', 'Fixed directional or omni unit'] },
    { label: 'Planning limit', values: ['Local RF conditions and target signal', 'RF environment, setup position and endurance', 'Clutter, terrain, mounting and target characteristics', 'Line of sight, weather and lighting', 'Legal authority, EMC, nearby communications and coverage geometry'] },
  ],
  workflowHeading: 'From mobile or fixed location to a countermeasure',
  workflowIntro: 'The locator establishes where the target is; the site then confirms it before any authorized jammer decision.',
  workflow: [
    { title: 'Detection', summary: 'A sensor creates an observation with time, source and available bearing, position or track data.' },
    { title: 'Identification', summary: 'The platform correlates handheld or fixed RF clues, radar tracks, map context and permitted-flight information.' },
    { title: 'Confirmation', summary: 'EO/IR cueing and operator review confirm the object, direction and current status where conditions allow.' },
    { title: 'Authorized Countermeasure', summary: 'Where permitted, the confirmed location is handed to the approved directional or omni-directional RF jammer workflow and the operator records the outcome.' },
  ],
  scenariosHeading: 'Two drone location scenarios',
  scenariosIntro: 'The required location evidence changes with the protected boundary and command workflow.',
  scenarios: [
    {
      title: 'Mobile Patrol & Temporary Location Post',
      summary: 'A handheld patrol detector and portable RF case support moving teams and temporary positions before handing confirmed data to the responsible operator.',
      image: '/products/02-drone-detection/portable-rf-detection-case.webp',
      imageAlt: 'Mobile patrol and portable RF drone location scenario',
      href: '/solutions/portable-drone-detection',
      linkLabel: 'View portable detection options',
      points: ['PL280H individual patrol alerts', 'Portable RF identification and location review', 'Defined escalation to an authorized response'],
    },
    {
      title: 'Industrial Perimeter Track Review',
      summary: 'A fixed layout follows activity around production areas and key perimeter routes while preserving a traceable event history.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Industrial perimeter drone locator solution scenario',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Stationary RF and radar correlation', 'EO/IR confirmation', 'Directional or omni jammer handoff where authorized'],
    },
  ],
  faqHeading: 'Drone Locator FAQ',
  faqs: [
    { question: 'Is this a lost-drone GPS locator?', answer: 'No. This is a protected-site workflow using mobile RF equipment or fixed RF, radar and EO/IR layers to locate and confirm activity.' },
    { question: 'Which two mobile locator options are available?', answer: 'The PL280H is a lightweight handheld RF detector for patrol users. The Portable RF Identification System is a hand-carried case with a larger display and identification, direction and positioning support.' },
    { question: 'Can RF direction finding provide an exact position?', answer: 'It can provide a bearing or supported position clue, but accuracy depends on the system design, signal conditions, antenna geometry, obstructions and local RF environment.' },
    { question: 'Why add radar to RF location?', answer: 'Radar contributes range, bearing and track continuity even when a recognizable control signal or cooperative identity broadcast is unavailable.' },
    { question: 'What countermeasure follows detection and location?', answer: 'Where legally authorized, a confirmed event may be handed to a Directional RF Jammer for a reviewed sector or an Omni-directional RF Jammer for approved area coverage.' },
    { question: 'What site information is needed?', answer: 'Provide the patrol method or fixed boundary, priority sectors, mounting points, terrain, permitted flights, network limits, jammer authority and operator handoff procedure.' },
  ],
  ctaLabel: 'Request Location Review',
};

export const droneShieldLanding: IntentLandingConfig = {
  handle: 'drone-shield',
  eyebrow: 'FIXED, PORTABLE & MOBILE C-UAS',
  h1: 'Drone Shield for Fixed, Portable & Mobile Deployment',
  purpose:
    'Compare fixed-site sensors, portable field units and vehicle-mounted C-UAS configurations for layered monitoring, confirmation and authorized-response coordination.',
  heroImage: '/products/rf-systems/portable-rf-field-unit-pro.webp',
  heroImageAlt: 'Portable C-UAS field unit in a layered Drone Shield configuration',
  heroFacts: ['Fixed-site coverage', 'Portable field deployment', 'Vehicle-mounted mobility'],
  applicationHeading: 'What makes a practical Drone Shield configuration?',
  answerBlock:
    'A practical drone shield is a layered site-protection architecture, not a guarantee that one product creates complete coverage. Fixed RF, radar, Remote ID and EO/IR equipment supports continuous monitoring of planned sectors. Portable field units support temporary posts, patrol teams and event deployments. Vehicle-mounted configurations help trained teams reposition between known operating points, but they require power, mounting, vibration, network and startup checks. After identification and visual confirmation, an authorized fixed-site project may add a Directional RF Jammer for a reviewed sector or an Omni-directional RF Jammer for approved area coverage. Selection begins with the site boundary, movement pattern, readiness time, evidence, staffing, nearby communications and local authority. Buildings, terrain, RF conditions, weather, mounting and target characteristics still affect performance.',
  applications: [
    { title: 'Continuous fixed-site coverage', summary: 'Monitor planned sectors with installed sensors, network links and a standing command workflow.' },
    { title: 'Temporary field protection', summary: 'Set up a portable unit for short-duration events, worksites or temporary posts.' },
    { title: 'Rapid-deployment team', summary: 'Carry an integrated field kit that joins evidence, event records and command handoff.' },
    { title: 'Vehicle-mounted patrol', summary: 'Reposition a configured sensor package between reviewed operating points.' },
  ],
  productsHeading: 'Reusable shield configurations',
  productsIntro: 'Choose the deployment format first, then confirm sensors, power, interfaces, evidence and response authority.',
  products: [
    {
      name: 'Portable C-UAS Field Shield',
      summary: 'A portable field unit for temporary sites and patrol teams that need local early warning and event review.',
      image: '/products/rf-systems/portable-rf-field-unit-basic.webp',
      imageAlt: 'Portable C-UAS Field Shield for temporary site protection',
      href: '/products/portable-low-altitude-monitoring-event-logging-shield',
      facts: ['Portable field deployment', 'RF awareness and event review', 'Temporary-site workflow'],
    },
    {
      name: 'Portable C-UAS Field Shield (Pro)',
      summary: 'A higher-coverage portable configuration for controlled sites requiring identification, positioning review and records.',
      image: '/products/rf-systems/portable-rf-field-unit-pro.webp',
      imageAlt: 'Portable C-UAS Field Shield Pro',
      href: '/products/portable-low-altitude-monitoring-event-logging-shield-pro',
      facts: ['Field-team configuration', 'Identification and position support', 'Platform and event records'],
    },
    {
      name: 'Stationary RF Identification System',
      summary: 'A fixed passive RF layer for continuous site awareness, supported identification and direction finding.',
      image: '/products/02-drone-detection/stationary-rf-detection-system.webp',
      imageAlt: 'Stationary RF identification system for fixed drone shield coverage',
      href: '/products/stationary-rf-detection-system',
      facts: ['Fixed-site passive monitoring', '360-degree horizontal coverage', 'Direction-finding support'],
    },
    {
      name: 'Integrated C-UAS Field Kit',
      summary: 'A rapid-deployment kit for RF awareness, target clues, tracking cues, event records and command coordination.',
      image: '/products/rf-systems/portable-integrated-rf-analysis-pro.webp',
      imageAlt: 'Integrated C-UAS field kit for rapid deployment',
      href: '/products/portable-integrated-detection-event-logging-pro-low-altitude-monitoring',
      facts: ['Rapid-deployment format', 'Integrated evidence workflow', 'Command-platform linkage'],
    },
    {
      name: 'Vehicle-Mounted C-UAS Configuration',
      summary: 'A project-configured mobile sensor and platform package for patrol routes and rapid repositioning.',
      image: '/solutions/low-altitude-airspace-monitoring/vehicle-mobile-cuas.webp',
      imageAlt: 'Vehicle-mounted C-UAS configuration for mobile drone shield patrol',
      href: '/products#vehicle-mounted-cuas',
      facts: ['Mobile multi-sector patrol', 'Project-specific power and mounting', 'Configurable sensor interfaces'],
    },
  ],
  comparisonHeading: 'Fixed, portable or vehicle-mounted?',
  comparisonIntro: 'Compare how the team operates before comparing individual product ranges.',
  comparisonColumns: ['Fixed-site system', 'Portable field unit', 'Integrated field kit', 'Vehicle-mounted system'],
  comparisonRows: [
    { label: 'Best fit', values: ['Continuous site monitoring', 'Temporary post or patrol', 'Rapid-deployment team', 'Mobile multi-sector patrol'] },
    { label: 'Readiness model', values: ['Installed and continuously available', 'Carry, position and start', 'Repeatable field setup', 'Reposition and validate at each stop'] },
    { label: 'Typical evidence', values: ['Multi-sensor fixed coverage', 'Local RF awareness and review', 'Integrated clues and event records', 'Configured mobile sensor package'] },
    { label: 'Key planning need', values: ['Mounting, power, network and blind zones', 'Transport, endurance and operator interface', 'Setup procedure and command linkage', 'Vehicle power, payload, vibration and horizon'] },
  ],
  workflowHeading: 'From shield alert to authorized response',
  workflowIntro: 'Every deployment format needs the same evidence, responsibility and escalation chain.',
  workflow: [
    { title: 'Detection', summary: 'The selected fixed, portable or mobile sensor layer creates an observation with available time and position data.' },
    { title: 'Identification', summary: 'The operator reviews supported RF, identity, map, track and permitted-flight information.' },
    { title: 'Confirmation', summary: 'Visual context and correlated site information establish the event status before escalation.' },
    { title: 'Authorized Response', summary: authorizedResponse },
  ],
  scenariosHeading: 'Two drone shield scenarios',
  scenariosIntro: 'Choose between installed continuity and mobile flexibility according to the site and operating team.',
  scenarios: [
    {
      title: 'Fixed Industrial Site Shield',
      summary: 'Installed RF, radar and EO/IR layers monitor priority sectors and pass confirmed events into the site command procedure.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Fixed industrial site drone shield solution scenario',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Continuous priority-sector monitoring', 'Multi-sensor confirmation', 'Standing command and record workflow'],
    },
    {
      title: 'Mobile Event-Area Shield',
      summary: 'Portable and vehicle-supported equipment covers planned positions during a time-bound event deployment.',
      image: '/cases/asian-games-security/case_stadium.webp',
      imageAlt: 'Mobile major-event drone shield solution scenario',
      href: '/cases/asian-games-security',
      points: ['Temporary operating positions', 'Field-team and command coordination', 'Defined setup and escalation checks'],
    },
  ],
  faqHeading: 'Drone Shield FAQ',
  faqs: [
    { question: 'Is a drone shield one product?', answer: 'Not necessarily. It may combine fixed, portable or mobile sensors, command software, operator roles and, where authorized, a directional or omni-directional RF jammer response.' },
    { question: 'When should a portable field unit be used?', answer: 'Use it when a team needs temporary monitoring, patrol support or a repeatable field post without permanent installation.' },
    { question: 'When is vehicle-mounted equipment appropriate?', answer: 'Choose it when a trained team must cover several planned sectors and can support vehicle power, mounting, network and startup checks.' },
    { question: 'Are coverage figures guaranteed?', answer: 'No. Buildings, terrain, RF noise, weather, mounting, target characteristics and test conditions affect usable coverage.' },
  ],
  ctaLabel: 'Request Shield Comparison',
};

export const droneJammerLanding: IntentLandingConfig = {
  handle: 'drone-jammer',
  eyebrow: 'DIRECTIONAL & OMNI RF JAMMERS',
  h1: 'Drone Jammer: Directional & Omni-Directional Options',
  purpose:
    'Compare Directional RF Jammer and Omni-directional RF Jammer options after RF, radar and EO/IR detection and confirmation in an authorized fixed-site project.',
  heroImage: '/products/rf-systems/directional-rf-unit.webp',
  heroImageAlt: 'Directional RF Jammer for an authorized fixed-site project',
  heroFacts: ['Directional RF suppression', 'Omni-directional RF suppression', 'Detection-first authorized workflow'],
  applicationHeading: 'Where does a drone jammer fit in the C-UAS workflow?',
  answerBlock:
    'A drone jammer belongs after detection, identification and confirmation—not at the start of the workflow. Fixed RF detection can provide signal and direction clues, radar adds range and continuous tracks, and EO/IR gives the operator visual evidence. Once the target and responsible operator are confirmed, an authorized project can select a Directional RF Jammer for a reviewed approach sector or an Omni-directional RF Jammer for approved area coverage. Selection must consider jurisdiction, protected-zone geometry, mounting, electromagnetic compatibility, nearby communications, safe distances, operator authority and the documented response procedure. N-TET can compare the two fixed-site jammer formats and their command-platform interfaces, but coverage and commissioning remain project-specific. The result should be a documented configuration that defines sensor evidence, jammer geometry, decision authority and event records.',
  applications: [
    { title: 'Directional RF suppression', summary: 'Use a directional jammer for a reviewed approach sector after target confirmation and operator approval.' },
    { title: 'Omni-directional RF suppression', summary: 'Use an omni-directional jammer only for an approved fixed-site area-coverage design.' },
    { title: 'Detection-led response', summary: 'Connect RF, radar and EO/IR confirmation to operator approval and jammer device status.' },
    { title: 'Project compliance review', summary: 'Document jurisdiction, spectrum, communications, safety and responsible-operator requirements.' },
  ],
  productsHeading: 'Two fixed-site drone jammer options',
  productsIntro: 'Choose directional or omni-directional RF suppression by coverage geometry, nearby communications and project authority.',
  products: [
    {
      name: 'Directional RF Jammer',
      summary: 'A project-configured directional RF suppression layer for a reviewed sector and authorized fixed-site workflow.',
      image: '/products/rf-systems/directional-rf-unit.webp',
      imageAlt: 'Directional RF Jammer',
      href: '/products/directional-rf-interference-device',
      facts: ['Directional sector geometry', 'Fixed-site project integration', 'Authorization and safety review required'],
    },
    {
      name: 'Omni-directional RF Jammer',
      summary: 'A project-configured omni-directional RF suppression layer for approved fixed-site zones and controlled operator procedures.',
      image: '/products/rf-systems/omni-directional-rf-unit.webp',
      imageAlt: 'Omni-directional RF Jammer',
      href: '/products/omni-directional-rf-interference-device',
      facts: ['Omni-directional area geometry', 'Fixed-site project integration', 'Authorization and safety review required'],
    },
  ],
  comparisonHeading: 'Directional vs. omni-directional drone jammer',
  comparisonIntro: 'This comparison supports early project selection; final engineering requires legal, spectrum and safety review.',
  comparisonColumns: ['Directional RF Jammer', 'Omni-directional RF Jammer'],
  comparisonRows: [
    { label: 'Coverage concept', values: ['Reviewed sector or approach direction', 'Reviewed area around a fixed installation'] },
    { label: 'Best fit', values: ['Sites that need controlled directional geometry', 'Sites with an approved area-coverage requirement'] },
    { label: 'Planning inputs', values: ['Sector drawing, aiming, mounting and exclusion zones', 'Area boundary, mounting, nearby systems and exclusion zones'] },
    { label: 'Required governance', values: ['Legal authority, EMC review, trained operator and approved procedure', 'Legal authority, EMC review, trained operator and approved procedure'] },
    { label: 'Platform role', values: ['Confirmed-event handoff and operator approval state', 'Confirmed-event handoff and operator approval state'] },
  ],
  workflowHeading: 'Detection to authorized jammer response',
  workflowIntro: 'The jammer remains downstream of RF and radar evidence, EO/IR confirmation and documented operator authority.',
  workflow: [
    { title: 'Detection', summary: 'RF, radar or Remote ID sources create an observation with time and available position or track data.' },
    { title: 'Identification', summary: 'The platform correlates sensor, map, identity and permitted-flight evidence while preserving uncertainty.' },
    { title: 'Confirmation', summary: 'EO/IR and operator review establish the event status and the responsible decision-maker.' },
    { title: 'Authorized Jammer Response', summary: 'A trained operator selects the approved directional or omni-directional jammer only after authority, safety conditions and device status are confirmed; the decision and outcome are recorded.' },
  ],
  scenariosHeading: 'Two authorized fixed-site scenarios',
  scenariosIntro: 'Both scenarios begin with multi-sensor confirmation and end with a controlled, documented decision.',
  scenarios: [
    {
      title: 'Directional Industrial Perimeter',
      summary: 'A reviewed approach sector uses a Directional RF Jammer downstream of fixed RF, radar and EO/IR confirmation.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Directional RF Jammer scenario at an industrial perimeter',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Defined sector and exclusion zones', 'Human confirmation and authority check', 'Controlled handoff and event record'],
    },
    {
      title: 'Omni-directional Protected Complex',
      summary: 'An approved fixed-site area uses an Omni-directional RF Jammer after reviewing surrounding systems, safe distances and operator procedures.',
      image: '/cases/airport-security-application/main-home.webp',
      imageAlt: 'Omni-directional RF Jammer planning scenario',
      href: '/cases/airport-security-application',
      points: ['Approved area boundary', 'EMC and communications review', 'Trained operator and documented procedure'],
    },
  ],
  faqHeading: 'Drone jammer planning FAQ',
  faqs: [
    { question: 'Who can purchase or operate this equipment?', answer: 'Eligibility depends on the jurisdiction and project authority. The buyer must confirm legal, spectrum, safety and operator requirements before detailed configuration.' },
    { question: 'How are directional and omni-directional jammers selected?', answer: 'Compare the approved coverage geometry, nearby communications, mounting, exclusion zones, platform interfaces and operating procedure.' },
    { question: 'Can a jammer act on every alert automatically?', answer: 'The project should not assume that. The workflow requires detection, identification, confirmation, responsible authority and an approved operator procedure before a jammer decision.' },
    { question: 'What is needed for an initial review?', answer: 'Provide the jurisdiction, protected boundary, reviewed sectors, nearby communications, mounting options, operator roles, authorization basis and safety requirements.' },
  ],
  ctaLabel: 'Request Jammer Comparison',
};
