import type { IntentLandingConfig } from './intentLandingPages';

const commandResponse =
  'The command platform correlates the confirmed track, displays sensor and device status, coordinates the configured response sequence, and records alarms, commands and outcomes.';

export const droneDefenderLanding: IntentLandingConfig = {
  handle: 'drone-defender',
  eyebrow: 'LAYERED DRONE DEFENDER',
  h1: 'Drone Defender for Layered Site Protection',
  purpose:
    'Combine RF detection, radar tracking, EO/IR confirmation and directional or omni-directional RF jammers in one layered site-protection workflow.',
  heroImage: '/solutions/low-altitude-airspace-monitoring/ntet-radar-back-side-facing-viewer-front-to-drone.webp',
  heroImageAlt: 'Layered Drone Defender configuration with radar and multi-sensor site monitoring',
  heroFacts: ['Multi-sensor detection & tracking', 'Directional and omni RF jammers', 'Integrated command & control'],
  applicationHeading: 'What does a layered Drone Defender configuration include?',
  answerBlock:
    'An integrated C-UAS defense system combines multi-source detection, target identification, continuous tracking, visual confirmation, command-and-control software and RF countermeasure equipment. Fixed RF sensors provide spectrum awareness, protocol identification and direction finding. Low-altitude radar adds range, bearing, altitude, speed and continuous tracks, while EO/IR provides visible and thermal imagery. The command platform correlates these inputs, evaluates the target track and links the confirmed event to a Directional RF Jammer for sector-focused coverage or an Omni-directional RF Jammer for 360-degree site coverage. Final design depends on the protected boundary, approach sectors, buildings, terrain, electromagnetic environment, mounting positions, nearby communications, staffing and system interfaces. Published ranges are reference conditions; site coverage should be confirmed through engineering design and field testing.',
  applications: [
    { title: 'Airport & transport boundaries', summary: 'Plan sector coverage, permitted-flight review and command-room handoff around operational zones.' },
    { title: 'Energy & industrial sites', summary: 'Combine perimeter awareness with traceable alert review around production and logistics areas.' },
    { title: 'Major venues & events', summary: 'Deploy time-bound monitoring with field-team coordination and a defined escalation path.' },
    { title: 'Government & managed sites', summary: 'Correlate identity, track and visual evidence before the responsible team makes a decision.' },
  ],
  productsHeading: 'Detection, tracking, confirmation and RF countermeasure layers',
  productsIntro: 'Build the sensor and command architecture first, then select the directional or omni-directional jammer geometry required by the site.',
  products: [
    {
      name: 'Stationary RF Identification System',
      summary: 'A fixed passive RF layer for signal awareness, supported identification, direction review and event handoff.',
      image: '/products/02-drone-detection/stationary-rf-detection-system.webp',
      imageAlt: 'Stationary RF identification system for layered drone protection',
      href: '/products/stationary-rf-detection-system',
      facts: ['Fixed-site passive RF sensing', '360-degree horizontal coverage', 'Identification and direction support'],
    },
    {
      name: 'Low-Altitude Early-Warning Radar',
      summary: 'A movement-tracking layer for early warning, trajectory review and cueing other sensors.',
      image: '/products/02-drone-detection/low-altitude-detection-radar.webp',
      imageAlt: 'Low-altitude radar for Drone Defender tracking',
      href: '/products/low-altitude-detection-radar-ku-band',
      facts: ['Range and bearing evidence', '360-degree azimuth coverage', 'Track data for platform handoff'],
    },
    {
      name: 'Electro-Optical Tracking System',
      summary: 'Visible-light and thermal imaging for operator confirmation, tracking and video evidence.',
      image: '/products/02-drone-detection/electro-optical-tracking-system.webp',
      imageAlt: 'Electro-optical and thermal tracking system for visual confirmation',
      href: '/products/composite-electro-optical-tracking-system',
      facts: ['Visible and thermal channels', 'Precision pan-tilt control', 'Radar cueing support'],
    },
    {
      name: 'Directional RF Jammer',
      summary: 'A fixed-site directional RF jammer for focused coverage of selected approach sectors.',
      image: '/products/rf-systems/directional-rf-unit.webp',
      imageAlt: 'Directional RF Jammer for a reviewed protection sector',
      href: '/products/directional-rf-interference-device',
      facts: ['Directional sector coverage', 'Fixed-site platform integration', 'Remote and linked control'],
    },
    {
      name: 'Omni-directional RF Jammer',
      summary: 'A fixed-site omni-directional RF jammer for 360-degree coverage around the protected area.',
      image: '/products/rf-systems/omni-directional-rf-unit.webp',
      imageAlt: 'Omni-directional RF Jammer for fixed-site area coverage',
      href: '/products/omni-directional-rf-interference-device',
      facts: ['360-degree area coverage', 'Fixed-site platform integration', 'Remote and linked control'],
    },
  ],
  comparisonHeading: 'Which protection layer closes which gap?',
  comparisonIntro: 'Compare evidence, site role and operating limits before selecting equipment.',
  comparisonColumns: ['RF detection', 'Radar', 'EO / IR', 'Directional jammer', 'Omni jammer'],
  comparisonRows: [
    { label: 'Primary role', values: ['Signal awareness, identity and direction clues', 'Movement, range, bearing and track', 'Visual and thermal confirmation', 'Sector-focused RF suppression', '360-degree RF suppression'] },
    { label: 'Workflow stage', values: ['Detection and identification', 'Detection and tracking', 'Confirmation', 'Directional RF countermeasure', 'Omni-directional RF countermeasure'] },
    { label: 'Key design input', values: ['RF noise, waveform coverage and quiet targets', 'Clutter, terrain, mounting and target characteristics', 'Line of sight, weather and target presentation', 'Sector geometry, aiming and nearby communications', 'Area geometry, mounting and nearby communications'] },
    { label: 'Typical format', values: ['Fixed-site passive sensor', 'Fixed or vehicle-supported sensor', 'Fixed confirmation layer', 'Fixed directional unit', 'Fixed omni-directional unit'] },
  ],
  workflowHeading: 'From detection to coordinated RF countermeasures',
  workflowIntro: 'RF, radar and EO/IR build a correlated target track before the command platform links the selected RF jammer.',
  workflow: [
    { title: 'Detection', summary: 'RF and radar create an observation with time, signal, range, bearing and available track data.' },
    { title: 'Identification', summary: 'The platform compares RF clues, movement, map context and permitted-flight information while preserving uncertainty.' },
    { title: 'Confirmation', summary: 'EO/IR cueing and operator review add visual context, status and notes before escalation.' },
    { title: 'RF Countermeasure', summary: 'The command platform links the confirmed target to the selected directional or omni-directional RF jammer and records device status, commands and outcomes.' },
  ],
  scenariosHeading: 'Two drone defender scenarios',
  scenariosIntro: 'The protection workflow stays consistent while sensor placement and handoff rules change by site.',
  scenarios: [
    {
      title: 'Airport Boundary Protection',
      summary: 'Fixed RF, radar and EO/IR layers cover approach sectors and link confirmed tracks to directional or omni-directional RF jammers.',
      image: '/cases/airport-security-application/main-home.webp',
      imageAlt: 'Airport boundary drone defender solution scenario',
      href: '/cases/airport-security-application',
      points: ['Sector and blind-zone design', 'RF, radar and visual correlation', 'Linked RF countermeasure control'],
    },
    {
      title: 'Industrial Perimeter Protection',
      summary: 'A continuous monitoring layout supports production areas, logistics routes and key perimeter sectors.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Industrial perimeter drone defender solution scenario',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Fixed RF, radar and EO/IR awareness', 'Confirmed target and continuous track', 'Configured jammer geometry and event record'],
    },
  ],
  faqHeading: 'Drone Defender FAQ',
  faqs: [
    { question: 'Is a Drone Defender one device?', answer: 'No. A complete system combines RF detection, radar tracking, EO/IR confirmation, command-and-control software and directional or omni-directional RF jammers selected for the site.' },
    { question: 'Can one configuration protect every site?', answer: 'No. Boundaries, approach sectors, terrain, buildings, RF conditions, mounting and operator procedures change the useful design.' },
    { question: 'What happens after a target is confirmed?', answer: 'The platform maintains the correlated track, displays sensor and device status, links the configured RF countermeasure equipment and records the complete event.' },
    { question: 'What is needed for a proposal?', answer: 'Provide a site map, protected sectors, normal flight activity, operating hours, mounting options, power and network limits, command interfaces and the required response mode.' },
  ],
  ctaLabel: 'Request Protection Plan',
};

export const droneLocatorLanding: IntentLandingConfig = {
  handle: 'drone-locator',
  eyebrow: 'MOBILE & FIXED DRONE LOCATION',
  h1: 'Drone Locator for Mobile & Fixed-Site Positioning',
  purpose:
    'Compare mobile and fixed-site Drone Locator configurations using RF direction finding, radar tracking, EO/IR confirmation and command-platform integration.',
  heroImage: '/products/02-drone-detection/portable-rf-detection-case.webp',
  heroImageAlt: 'Portable RF drone detection and location equipment for mobile deployment',
  heroFacts: ['Mobile RF direction finding', 'Fixed RF, radar and EO/IR', 'Jammer and platform linkage'],
  applicationHeading: 'What does a site drone locator need to show?',
  answerBlock:
    'A Drone Locator project can begin with mobile equipment or a fixed sensor layout. The PL280H gives an individual patrol user lightweight RF alerts, while the Portable RF Identification System adds a larger display, protocol identification, direction finding and positioning support for a temporary post. Fixed sites combine stationary RF detection with radar range, bearing, altitude and continuous track data, then cue EO/IR for visual confirmation. The command platform correlates these sources by time and map position and maintains a unified target track. After confirmation, the track can be linked to a Directional RF Jammer for selected sectors or an Omni-directional RF Jammer for 360-degree fixed-site coverage. Buildings, terrain, RF noise, radar clutter, line of sight, mounting geometry and sensor interfaces all affect the final configuration.',
  applications: [
    { title: 'Individual mobile patrol', summary: 'Use the PL280H for lightweight local RF alerts while one operator is moving.' },
    { title: 'Temporary location post', summary: 'Use the portable RF case for identification, direction and position review with a larger display.' },
    { title: 'Fixed perimeter location', summary: 'Combine stationary RF, radar tracks and EO/IR confirmation around planned sectors.' },
    { title: 'RF countermeasure linkage', summary: 'Link the confirmed target track to the configured directional or omni-directional RF jammer.' },
  ],
  productsHeading: 'Mobile locators, fixed sensors and jammer options',
  productsIntro: 'Start with the mobile location format, add fixed RF, radar and EO/IR where continuous coverage is required, then define the command and countermeasure interfaces.',
  products: [
    {
      name: 'PL280H Handheld RF Detection System',
      summary: 'A lightweight passive RF detector for individual patrol, local alerts and rapid movement between sectors.',
      image: '/products/02-drone-detection/handheld-rf-detection-system-pl280h.webp',
      imageAlt: 'PL280H handheld RF drone detector for mobile patrol',
      href: '/products/handheld-rf-detection-system-mini',
      facts: ['Handheld patrol format', 'Passive RF monitoring', 'Visual, audible and vibration alerts'],
    },
    {
      name: 'Portable RF Identification System',
      summary: 'A hand-carried RF system with integrated display for identification, direction and positioning support at temporary posts.',
      image: '/products/02-drone-detection/portable-rf-detection-case.webp',
      imageAlt: 'Portable RF identification and drone location system',
      href: '/products/portable-rf-detection-case',
      facts: ['Hand-carried field case', 'Identification and positioning support', 'Integrated 13.3-inch display'],
    },
    {
      name: 'Stationary RF Identification System',
      summary: 'Fixed passive RF sensing for supported identification, direction finding and mapped event review.',
      image: '/products/02-drone-detection/stationary-rf-detection-system.webp',
      imageAlt: 'Stationary RF identification and direction-finding system',
      href: '/products/stationary-rf-detection-system',
      facts: ['Passive RF awareness', 'Direction-finding support', 'Fixed-site event handoff'],
    },
    {
      name: 'Low-Altitude Early-Warning Radar',
      summary: 'Provides movement, range, bearing and track data for non-cooperative target positioning.',
      image: '/products/02-drone-detection/low-altitude-detection-radar.webp',
      imageAlt: 'Low-altitude radar for drone track positioning',
      href: '/products/low-altitude-detection-radar-ku-band',
      facts: ['Range and bearing', 'Trajectory tracking', 'Multi-sensor cueing'],
    },
    {
      name: 'Electro-Optical Tracking System',
      summary: 'Adds visible and thermal imagery for operator confirmation and target tracking.',
      image: '/products/02-drone-detection/electro-optical-tracking-system.webp',
      imageAlt: 'Electro-optical system confirming a located drone target',
      href: '/products/composite-electro-optical-tracking-system',
      facts: ['Visible and thermal channels', 'Precision pan-tilt tracking', 'Radar linkage support'],
    },
    {
      name: 'Directional RF Jammer',
      summary: 'A directional RF suppression option for a confirmed target in a reviewed sector.',
      image: '/products/rf-systems/directional-rf-unit.webp',
      imageAlt: 'Directional RF Jammer for a selected target sector',
      href: '/products/directional-rf-interference-device',
      facts: ['Directional countermeasure geometry', 'Fixed-site integration', 'Remote and linked control'],
    },
    {
      name: 'Omni-directional RF Jammer',
      summary: 'An omni-directional RF suppression option for 360-degree fixed-site coverage.',
      image: '/products/rf-systems/omni-directional-rf-unit.webp',
      imageAlt: 'Omni-directional RF Jammer for fixed-site area coverage',
      href: '/products/omni-directional-rf-interference-device',
      facts: ['360-degree countermeasure geometry', 'Fixed-site integration', 'Remote and linked control'],
    },
  ],
  comparisonHeading: 'Which mobile, fixed or jammer layer fits the task?',
  comparisonIntro: 'Compare operator mobility, target location data, confirmation method and system interfaces—not range alone.',
  comparisonColumns: ['Handheld RF', 'Portable RF case', 'Fixed RF + radar', 'EO / IR', 'RF jammer'],
  comparisonRows: [
    { label: 'Best role', values: ['Individual mobile alerting', 'Temporary identification and location post', 'Continuous bearing and track coverage', 'Visual confirmation', 'RF countermeasure'] },
    { label: 'Primary output', values: ['Local RF alert', 'RF identity, direction and position clues', 'RF clues plus radar range, bearing and track', 'Visible and thermal imagery', 'Directional or area RF suppression'] },
    { label: 'Deployment', values: ['Handheld patrol', 'Hand-carried field case', 'Installed site sensors', 'Fixed cueing system', 'Fixed directional or omni unit'] },
    { label: 'Planning input', values: ['Local RF conditions and target signal', 'RF environment, setup position and endurance', 'Clutter, terrain, mounting and target characteristics', 'Line of sight, weather and lighting', 'Coverage geometry, EMC and nearby communications'] },
  ],
  workflowHeading: 'From mobile or fixed location to a countermeasure',
  workflowIntro: 'The locator establishes where the target is; the command platform then confirms and links the track to the configured response equipment.',
  workflow: [
    { title: 'Detection', summary: 'A sensor creates an observation with time, source and available bearing, position or track data.' },
    { title: 'Identification', summary: 'The platform correlates handheld or fixed RF clues, radar tracks, map context and permitted-flight information.' },
    { title: 'Confirmation', summary: 'EO/IR cueing and operator review confirm the object, direction and current status where conditions allow.' },
    { title: 'RF Countermeasure', summary: 'The confirmed location is linked to the configured directional or omni-directional RF jammer, while the platform records commands, device status and outcomes.' },
  ],
  scenariosHeading: 'Two drone location scenarios',
  scenariosIntro: 'The required location evidence changes with the protected boundary and command workflow.',
  scenarios: [
    {
      title: 'Mobile Patrol & Temporary Location Post',
      summary: 'A handheld patrol detector and portable RF case support moving teams and temporary positions before handing confirmed data to the responsible operator.',
      image: '/products/02-drone-detection/portable-rf-detection-case.webp',
      imageAlt: 'Mobile patrol and portable RF drone location scenario',
      href: '/solutions/portable-drone-detection',
      linkLabel: 'View portable detection options',
      points: ['PL280H individual patrol alerts', 'Portable RF identification and location review', 'Defined command-platform handoff'],
    },
    {
      title: 'Industrial Perimeter Track Review',
      summary: 'A fixed layout follows activity around production areas and key perimeter routes while preserving a traceable event history.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Industrial perimeter drone locator solution scenario',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Stationary RF and radar correlation', 'EO/IR confirmation', 'Directional or omni jammer linkage'],
    },
  ],
  faqHeading: 'Drone Locator FAQ',
  faqs: [
    { question: 'Is this a lost-drone GPS locator?', answer: 'No. This is a protected-site workflow using mobile RF equipment or fixed RF, radar and EO/IR layers to locate and confirm activity.' },
    { question: 'Which two mobile locator options are available?', answer: 'The PL280H is a lightweight handheld RF detector for patrol users. The Portable RF Identification System is a hand-carried case with a larger display and identification, direction and positioning support.' },
    { question: 'Can RF direction finding provide an exact position?', answer: 'It can provide a bearing or supported position clue, but accuracy depends on the system design, signal conditions, antenna geometry, obstructions and local RF environment.' },
    { question: 'Why add radar to RF location?', answer: 'Radar contributes range, bearing and track continuity even when a recognizable control signal or cooperative identity broadcast is unavailable.' },
    { question: 'What countermeasure follows detection and location?', answer: 'A confirmed target track can be linked to a Directional RF Jammer for selected sectors or an Omni-directional RF Jammer for 360-degree fixed-site coverage.' },
    { question: 'What site information is needed?', answer: 'Provide the patrol method or fixed boundary, priority sectors, mounting points, terrain, normal flight activity, network limits, response mode and command-platform interfaces.' },
  ],
  ctaLabel: 'Request Location Review',
};

export const droneShieldLanding: IntentLandingConfig = {
  handle: 'drone-shield',
  eyebrow: 'FIXED, PORTABLE & MOBILE C-UAS',
  h1: 'Drone Shield for Fixed, Portable & Mobile Deployment',
  purpose:
    'Compare fixed-site, portable and vehicle-mounted Drone Shield configurations for multi-sensor detection, target tracking, command and coordinated response.',
  heroImage: '/products/rf-systems/portable-rf-field-unit-pro.webp',
  heroImageAlt: 'Portable C-UAS field unit in a layered Drone Shield configuration',
  heroFacts: ['Fixed-site coverage', 'Portable field deployment', 'Vehicle-mounted mobility'],
  applicationHeading: 'What makes a practical Drone Shield configuration?',
  answerBlock:
    'A practical Drone Shield is a layered site-protection architecture rather than a single product. Fixed RF, radar, Remote ID and EO/IR equipment provides continuous detection, identification and tracking across planned sectors. Portable field units support temporary posts, patrol teams and event deployments. Vehicle-mounted configurations let teams reposition between operating points while maintaining sensor, platform and communications links. After target identification and visual confirmation, a Directional RF Jammer can provide focused sector coverage or an Omni-directional RF Jammer can provide 360-degree fixed-site coverage. Selection begins with the site boundary, approach directions, readiness time, staffing, power, network, nearby communications and required response mode. Buildings, terrain, RF conditions, weather, mounting geometry and target characteristics still affect performance.',
  applications: [
    { title: 'Continuous fixed-site coverage', summary: 'Monitor planned sectors with installed sensors, network links and a standing command workflow.' },
    { title: 'Temporary field protection', summary: 'Set up a portable unit for short-duration events, worksites or temporary posts.' },
    { title: 'Rapid-deployment team', summary: 'Carry an integrated field kit that joins evidence, event records and command handoff.' },
    { title: 'Vehicle-mounted patrol', summary: 'Reposition a configured sensor package between reviewed operating points.' },
  ],
  productsHeading: 'Reusable shield configurations',
  productsIntro: 'Choose the deployment format first, then define sensors, power, network, command interfaces and response equipment.',
  products: [
    {
      name: 'Portable C-UAS Field Shield',
      summary: 'A portable field unit for temporary sites and patrol teams that need local early warning and event review.',
      image: '/products/rf-systems/portable-rf-field-unit-basic.webp',
      imageAlt: 'Portable C-UAS Field Shield for temporary site protection',
      href: '/products/portable-low-altitude-monitoring-event-logging-shield',
      facts: ['Portable field deployment', 'RF awareness and event review', 'Temporary-site workflow'],
    },
    {
      name: 'Portable C-UAS Field Shield (Pro)',
      summary: 'A higher-coverage portable configuration for controlled sites requiring identification, positioning review and records.',
      image: '/products/rf-systems/portable-rf-field-unit-pro.webp',
      imageAlt: 'Portable C-UAS Field Shield Pro',
      href: '/products/portable-low-altitude-monitoring-event-logging-shield-pro',
      facts: ['Field-team configuration', 'Identification and position support', 'Platform and event records'],
    },
    {
      name: 'Stationary RF Identification System',
      summary: 'A fixed passive RF layer for continuous site awareness, supported identification and direction finding.',
      image: '/products/02-drone-detection/stationary-rf-detection-system.webp',
      imageAlt: 'Stationary RF identification system for fixed drone shield coverage',
      href: '/products/stationary-rf-detection-system',
      facts: ['Fixed-site passive monitoring', '360-degree horizontal coverage', 'Direction-finding support'],
    },
    {
      name: 'Integrated C-UAS Field Kit',
      summary: 'A rapid-deployment kit for RF awareness, target clues, tracking cues, event records and command coordination.',
      image: '/products/rf-systems/portable-integrated-rf-analysis-pro.webp',
      imageAlt: 'Integrated C-UAS field kit for rapid deployment',
      href: '/products/portable-integrated-detection-event-logging-pro-low-altitude-monitoring',
      facts: ['Rapid-deployment format', 'Integrated evidence workflow', 'Command-platform linkage'],
    },
    {
      name: 'Vehicle-Mounted C-UAS Configuration',
      summary: 'A project-configured mobile sensor and platform package for patrol routes and rapid repositioning.',
      image: '/solutions/low-altitude-airspace-monitoring/vehicle-mobile-cuas.webp',
      imageAlt: 'Vehicle-mounted C-UAS configuration for mobile drone shield patrol',
      href: '/products#vehicle-mounted-cuas',
      facts: ['Mobile multi-sector patrol', 'Project-specific power and mounting', 'Configurable sensor interfaces'],
    },
  ],
  comparisonHeading: 'Fixed, portable or vehicle-mounted?',
  comparisonIntro: 'Compare how the team operates before comparing individual product ranges.',
  comparisonColumns: ['Fixed-site system', 'Portable field unit', 'Integrated field kit', 'Vehicle-mounted system'],
  comparisonRows: [
    { label: 'Best fit', values: ['Continuous site monitoring', 'Temporary post or patrol', 'Rapid-deployment team', 'Mobile multi-sector patrol'] },
    { label: 'Readiness model', values: ['Installed and continuously available', 'Carry, position and start', 'Repeatable field setup', 'Reposition and validate at each stop'] },
    { label: 'Typical evidence', values: ['Multi-sensor fixed coverage', 'Local RF awareness and review', 'Integrated clues and event records', 'Configured mobile sensor package'] },
    { label: 'Key planning need', values: ['Mounting, power, network and blind zones', 'Transport, endurance and operator interface', 'Setup procedure and command linkage', 'Vehicle power, payload, vibration and horizon'] },
  ],
  workflowHeading: 'From Drone Shield detection to coordinated response',
  workflowIntro: 'Every deployment format follows the same detection, identification, tracking, confirmation and command sequence.',
  workflow: [
    { title: 'Detection', summary: 'The selected fixed, portable or mobile sensor layer creates an observation with available time and position data.' },
    { title: 'Identification', summary: 'The operator reviews supported RF, identity, map, track and permitted-flight information.' },
    { title: 'Confirmation', summary: 'Visual context and correlated site information establish the event status before escalation.' },
    { title: 'Command & Response', summary: commandResponse },
  ],
  scenariosHeading: 'Two drone shield scenarios',
  scenariosIntro: 'Choose between installed continuity and mobile flexibility according to the site and operating team.',
  scenarios: [
    {
      title: 'Fixed Industrial Site Shield',
      summary: 'Installed RF, radar and EO/IR layers monitor priority sectors and pass confirmed events into the site command procedure.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Fixed industrial site drone shield solution scenario',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Continuous priority-sector monitoring', 'Multi-sensor confirmation', 'Standing command and record workflow'],
    },
    {
      title: 'Mobile Event-Area Shield',
      summary: 'Portable and vehicle-supported equipment covers planned positions during a time-bound event deployment.',
      image: '/cases/asian-games-security/case_stadium.webp',
      imageAlt: 'Mobile major-event drone shield solution scenario',
      href: '/cases/asian-games-security',
      points: ['Temporary operating positions', 'Field-team and command coordination', 'Defined setup and escalation checks'],
    },
  ],
  faqHeading: 'Drone Shield FAQ',
  faqs: [
    { question: 'Is a Drone Shield one product?', answer: 'Not necessarily. A complete configuration can combine fixed, portable or mobile sensors, command software and directional or omni-directional RF jammers selected for the site.' },
    { question: 'When should a portable field unit be used?', answer: 'Use it when a team needs temporary monitoring, patrol support or a repeatable field post without permanent installation.' },
    { question: 'When is vehicle-mounted equipment appropriate?', answer: 'Choose it when a trained team must cover several planned sectors and can support vehicle power, mounting, network and startup checks.' },
    { question: 'Are coverage figures guaranteed?', answer: 'No. Buildings, terrain, RF noise, weather, mounting, target characteristics and test conditions affect usable coverage.' },
  ],
  ctaLabel: 'Request Shield Comparison',
};

export const droneJammerLanding: IntentLandingConfig = {
  handle: 'drone-jammer',
  eyebrow: 'DIRECTIONAL & OMNI RF JAMMERS',
  h1: 'Drone Jammer: Directional & Omni-Directional Options',
  purpose:
    'Compare Directional RF Jammer and Omni-directional RF Jammer options for fixed-site C-UAS integration, linked control and coordinated response.',
  heroImage: '/products/rf-systems/directional-rf-unit.webp',
  heroImageAlt: 'Directional RF Jammer for fixed-site C-UAS integration',
  heroFacts: ['Directional RF suppression', 'Omni-directional RF suppression', 'Detection and platform linkage'],
  applicationHeading: 'Where does a drone jammer fit in the C-UAS workflow?',
  answerBlock:
    'A Drone Jammer belongs downstream of detection, identification and target confirmation. Fixed RF detection provides spectrum and direction information, radar adds range, altitude, speed and continuous tracks, and EO/IR provides visible and thermal confirmation. The command platform then links the target track to a Directional RF Jammer for focused approach-sector coverage or an Omni-directional RF Jammer for 360-degree fixed-site coverage. Selection should consider protected-zone geometry, mounting, electromagnetic compatibility, nearby communications, output configuration, platform interfaces and operating mode. N-TET supports the engineering comparison, system integration, linked control and commissioning of both fixed-site jammer formats. The final design defines sensor inputs, jammer coverage geometry, command logic, device status and event records.',
  applications: [
    { title: 'Directional RF suppression', summary: 'Use a directional jammer for focused coverage of selected approach sectors.' },
    { title: 'Omni-directional RF suppression', summary: 'Use an omni-directional jammer for 360-degree fixed-site coverage.' },
    { title: 'Detection-led response', summary: 'Connect RF, radar and EO/IR confirmation to jammer control and device status.' },
    { title: 'Command-platform integration', summary: 'Integrate target tracks, alarms, control commands, equipment status and event records.' },
  ],
  productsHeading: 'Two fixed-site drone jammer options',
  productsIntro: 'Choose directional or omni-directional RF suppression by coverage geometry, mounting, nearby communications and platform interface.',
  products: [
    {
      name: 'Directional RF Jammer',
      summary: 'A project-configured directional RF suppression layer for focused sector coverage and fixed-site integration.',
      image: '/products/rf-systems/directional-rf-unit.webp',
      imageAlt: 'Directional RF Jammer',
      href: '/products/directional-rf-interference-device',
      facts: ['Directional sector geometry', 'Fixed-site project integration', 'Remote and linked control'],
    },
    {
      name: 'Omni-directional RF Jammer',
      summary: 'A project-configured omni-directional RF suppression layer for 360-degree fixed-site coverage.',
      image: '/products/rf-systems/omni-directional-rf-unit.webp',
      imageAlt: 'Omni-directional RF Jammer',
      href: '/products/omni-directional-rf-interference-device',
      facts: ['Omni-directional area geometry', 'Fixed-site project integration', 'Remote and linked control'],
    },
  ],
  comparisonHeading: 'Directional vs. omni-directional drone jammer',
  comparisonIntro: 'Compare coverage geometry, installation, electromagnetic environment, command interfaces and operating mode.',
  comparisonColumns: ['Directional RF Jammer', 'Omni-directional RF Jammer'],
  comparisonRows: [
    { label: 'Coverage concept', values: ['Focused sector or approach direction', '360-degree area around a fixed installation'] },
    { label: 'Best fit', values: ['Sites that need directional coverage geometry', 'Sites that need omni-directional area coverage'] },
    { label: 'Planning inputs', values: ['Sector drawing, aiming, mounting and exclusion zones', 'Area boundary, mounting, nearby systems and exclusion zones'] },
    { label: 'Platform role', values: ['Target-track handoff, control and device status', 'Target-track handoff, control and device status'] },
  ],
  workflowHeading: 'Detection, confirmation and jammer response',
  workflowIntro: 'The jammer remains downstream of RF and radar detection, EO/IR confirmation and command-platform correlation.',
  workflow: [
    { title: 'Detection', summary: 'RF, radar or Remote ID sources create an observation with time and available position or track data.' },
    { title: 'Identification', summary: 'The platform correlates sensor, map, identity and permitted-flight evidence while preserving uncertainty.' },
    { title: 'Confirmation', summary: 'EO/IR and operator review establish the event status and the responsible decision-maker.' },
    { title: 'Jammer Response', summary: 'The command platform links the confirmed target to the selected directional or omni-directional jammer and records control commands, device status and outcomes.' },
  ],
  scenariosHeading: 'Two fixed-site jammer configurations',
  scenariosIntro: 'Both configurations begin with multi-sensor confirmation and use command-platform linkage for control and event records.',
  scenarios: [
    {
      title: 'Directional Industrial Perimeter',
      summary: 'A selected approach sector uses a Directional RF Jammer downstream of fixed RF, radar and EO/IR confirmation.',
      image: '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
      imageAlt: 'Directional RF Jammer scenario at an industrial perimeter',
      href: '/cases/brazil-refinery-low-altitude-monitoring',
      points: ['Defined sector and aiming geometry', 'Multi-sensor target confirmation', 'Linked control and event record'],
    },
    {
      title: 'Omni-directional Protected Complex',
      summary: 'A fixed-site area uses an Omni-directional RF Jammer after reviewing mounting, surrounding systems and communications interfaces.',
      image: '/cases/airport-security-application/main-home.webp',
      imageAlt: 'Omni-directional RF Jammer planning scenario',
      href: '/cases/airport-security-application',
      points: ['Defined coverage boundary', 'EMC and communications review', 'Platform linkage and device status'],
    },
  ],
  faqHeading: 'Drone jammer planning FAQ',
  faqs: [
    { question: 'How are directional and omni-directional jammers selected?', answer: 'Compare coverage geometry, nearby communications, mounting position, aiming or area coverage, output configuration and command-platform interfaces.' },
    { question: 'Can the jammer be linked to the detection system?', answer: 'Yes. The command platform can correlate RF, radar and EO/IR data, maintain the target track, issue control commands and display jammer status in one interface.' },
    { question: 'What is needed for an initial review?', answer: 'Provide the protected boundary, priority sectors, nearby communications, mounting options, power and network conditions, platform interfaces and the required operating mode.' },
  ],
  ctaLabel: 'Request Jammer Comparison',
};
