export const solutionCenterGroups = [
  {
    id: 'uav-inspection-patrol',
    labelKey: 'uavInspectionPatrol',
    fallbackLabel: 'UAV Inspection & Patrol',
    eyebrowKey: 'uavIndustryApplications',
    fallbackEyebrow: 'UAV Industry Applications',
    descriptionKey: 'uavInspectionPatrolDesc',
    fallbackDescription: 'Recurring aerial patrol, corridor inspection, and field monitoring for utilities, water resources, coastal teams, and industrial assets.',
    categoryHref: undefined,
    handles: [
      'power-line-uav-intelligent-inspection-solution',
      'smart-substation-unattended-uav-inspection-solution',
      'water-conservancy-river-lake-uav-monitoring-solution',
      'uav-maritime-patrol',
    ],
  },
  {
    id: 'uav-emergency-response',
    labelKey: 'uavEmergencyResponse',
    fallbackLabel: 'UAV Emergency Response',
    eyebrowKey: 'uavIndustryApplications',
    fallbackEyebrow: 'UAV Industry Applications',
    descriptionKey: 'uavEmergencyResponseDesc',
    fallbackDescription: 'Rapid aerial response for firefighting support, search and rescue, post-disaster communications, and night emergency lighting.',
    categoryHref: undefined,
    handles: [
      'urban-high-rise-firefighting-emergency-uav-solution',
      'disaster-site-search-rescue-reconnaissance-uav-solution',
      'post-disaster-emergency-communication-support-uav-solution',
      'night-emergency-lighting-support-uav-solution',
    ],
  },
  {
    id: 'critical-infrastructure-protection',
    labelKey: 'criticalInfrastructure',
    fallbackLabel: 'Critical Infrastructure Protection',
    eyebrowKey: 'infrastructure',
    fallbackEyebrow: 'Infrastructure Protection',
    descriptionKey: 'criticalInfrastructureDesc',
    fallbackDescription: 'UAV inspection, airspace monitoring, and perimeter intelligence for energy, petrochemical, water-conservancy, and industrial facilities.',
    categoryHref: '/solutions/category/02_InfrastructureProtection',
    handles: [
      'chemical-plant-protection',
      'oil-production-base-protection',
      'hydroelectric-dam-protection',
    ],
  },
  {
    id: 'key-area-security',
    labelKey: 'keyAreaSecurity',
    fallbackLabel: 'Key Area Security',
    eyebrowKey: 'keyArea',
    fallbackEyebrow: 'Key Area Security',
    descriptionKey: 'keyAreaSecurityDesc',
    fallbackDescription: 'Security screening, EO/IR monitoring, and low-altitude airspace awareness for judicial sites, major events, airport checkpoints, and transport hubs.',
    categoryHref: '/solutions/category/03_KeyAreaSecurity',
    handles: [
      'judicial-sector-security',
      'sports-event-security',
      'airport-security-protection',
    ],
  },
] as const;

export const englishCuasSolutionCenterGroups = [
  { id: 'critical-infrastructure', labelKey: 'cuasCriticalInfrastructure', fallbackLabel: 'Critical Infrastructure', eyebrowKey: 'infrastructure', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasCriticalInfrastructureDesc', fallbackDescription: 'Layered airspace awareness for essential facilities and complex industrial perimeters.', categoryHref: undefined, handles: ['critical-infrastructure-airspace-monitoring'] },
  { id: 'power-plants', labelKey: 'cuasPowerPlants', fallbackLabel: 'Power Plants', eyebrowKey: 'infrastructure', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasPowerPlantsDesc', fallbackDescription: 'Continuous monitoring for generation sites, switchyards, dams and renewable assets.', categoryHref: undefined, handles: ['power-plant-airspace-monitoring'] },
  { id: 'airports', labelKey: 'cuasAirports', fallbackLabel: 'Airports', eyebrowKey: 'keyArea', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasAirportsDesc', fallbackDescription: 'Multi-sensor airport perimeter and approach-area awareness with operator verification.', categoryHref: undefined, handles: ['airport-security-protection'] },
  { id: 'borders', labelKey: 'cuasBorders', fallbackLabel: 'Borders', eyebrowKey: 'keyArea', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasBordersDesc', fallbackDescription: 'Fixed, mobile and portable monitoring for remote sectors and changing field operations.', categoryHref: undefined, handles: ['border-airspace-monitoring'] },
  { id: 'public-safety', labelKey: 'cuasPublicSafety', fallbackLabel: 'Public Safety', eyebrowKey: 'keyArea', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasPublicSafetyDesc', fallbackDescription: 'Deployable airspace awareness for municipal operations and temporary public-security zones.', categoryHref: undefined, handles: ['public-safety-airspace-monitoring'] },
  { id: 'prisons', labelKey: 'cuasPrisons', fallbackLabel: 'Prisons', eyebrowKey: 'keyArea', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasPrisonsDesc', fallbackDescription: 'Persistent perimeter monitoring for correctional and detention facilities.', categoryHref: undefined, handles: ['correctional-facility-airspace-monitoring'] },
  { id: 'ports', labelKey: 'cuasPorts', fallbackLabel: 'Port Security', eyebrowKey: 'infrastructure', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasPortsDesc', fallbackDescription: 'Coastal and terminal airspace awareness for ports, harbors and logistics zones.', categoryHref: undefined, handles: ['port-airspace-monitoring'] },
  { id: 'mass-events', labelKey: 'cuasMassEvents', fallbackLabel: 'Mass Events', eyebrowKey: 'keyArea', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasMassEventsDesc', fallbackDescription: 'Rapidly deployable monitoring for stadiums, festivals and major gatherings.', categoryHref: undefined, handles: ['mass-event-airspace-monitoring'] },
  { id: 'vip-private-property', labelKey: 'cuasVipPrivateProperty', fallbackLabel: 'VIP & Private Property', eyebrowKey: 'keyArea', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasVipPrivatePropertyDesc', fallbackDescription: 'Discreet fixed, portable or mobile awareness for private and temporary locations.', categoryHref: undefined, handles: ['vip-private-property-airspace-monitoring'] },
  { id: 'enterprises', labelKey: 'cuasEnterprises', fallbackLabel: 'Enterprises', eyebrowKey: 'infrastructure', fallbackEyebrow: 'C-UAS Applications', descriptionKey: 'cuasEnterprisesDesc', fallbackDescription: 'Configurable monitoring for factories, campuses, warehouses and research facilities.', categoryHref: undefined, handles: ['enterprise-airspace-monitoring'] },
] as const;

export type SolutionCenterGroupId = (typeof solutionCenterGroups)[number]['id'];

export const solutionCenterImageByHandle: Record<string, string> = {
  'power-line-uav-intelligent-inspection-solution': '/solutions/solutions/Power Line UAV Intelligent Inspection.webp',
  'smart-substation-unattended-uav-inspection-solution': '/solutions/solutions/Smart Substation Unattended Inspection.webp',
  'water-conservancy-river-lake-uav-monitoring-solution': '/solutions/solutions/Water Conservancy & River-Lake Monitoring.webp',
  'uav-maritime-patrol': '/solutions/solutions/border-patrol-coastal-monitoring.webp',
  'urban-high-rise-firefighting-emergency-uav-solution': '/solutions/solutions/Urban High-Rise Firefighting & Rescue.webp',
  'disaster-site-search-rescue-reconnaissance-uav-solution': '/solutions/solutions/Disaster-Site Search, Rescue & Reconnaissance.webp',
  'post-disaster-emergency-communication-support-uav-solution': '/solutions/solutions/Post-Disaster Emergency Communication Support.webp',
  'night-emergency-lighting-support-uav-solution': '/solutions/solutions/Night Emergency Lighting Support.webp',
  'chemical-plant-protection': '/cases/brazil-refinery-airspace-monitoring/main-home.webp',
  'oil-production-base-protection': '/cases/pakistan-power-plant-airspace-monitoring/main-home.webp',
  'sports-event-security': '/cases/asian-games-security/main.webp',
  'airport-security-protection': '/solutions/cuas-applications/airport-security-protection/hero.webp',
  'critical-infrastructure-airspace-monitoring': '/solutions/cuas-applications/critical-infrastructure-airspace-monitoring/hero.webp',
  'power-plant-airspace-monitoring': '/solutions/cuas-applications/power-plant-airspace-monitoring/hero.webp',
  'border-airspace-monitoring': '/solutions/cuas-applications/border-airspace-monitoring/hero.webp',
  'public-safety-airspace-monitoring': '/solutions/cuas-applications/public-safety-airspace-monitoring/hero.webp',
  'correctional-facility-airspace-monitoring': '/solutions/cuas-applications/correctional-facility-airspace-monitoring/hero.webp',
  'port-airspace-monitoring': '/solutions/cuas-applications/port-airspace-monitoring/hero.webp',
  'mass-event-airspace-monitoring': '/solutions/cuas-applications/mass-event-airspace-monitoring/hero.webp',
  'vip-private-property-airspace-monitoring': '/solutions/cuas-applications/vip-private-property-airspace-monitoring/hero.webp',
  'enterprise-airspace-monitoring': '/solutions/cuas-applications/enterprise-airspace-monitoring/hero.webp',
};

export const solutionCenterCardImageByHandle: Record<string, string> = {
  'critical-infrastructure-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/01 Critical Infrastructure.webp',
  'power-plant-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/02 Power Plants.webp',
  'airport-security-protection': '/solutions/cuas-applications/cuas_solution_center/03 Airports.webp',
  'border-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/04 Borders.webp',
  'public-safety-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/05 Public Safety.webp',
  'correctional-facility-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/06 Prisons.webp',
  'port-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/07 Ports.webp',
  'mass-event-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/08 Mass Events.webp',
  'vip-private-property-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/09 VIPs & Private Property.webp',
  'enterprise-airspace-monitoring': '/solutions/cuas-applications/cuas_solution_center/10 Enterprises.webp',
};
