export const products = [
    {
        top: 'RF Spectrum Monitoring',
        top_ru: 'Радиочастотный мониторинг',
        main: 'Stationary RF Identification System',
        main_ru: 'Стационарная система радиочастотной идентификации',
        desc: 'Fixed-site RF spectrum analysis, alert review and event recording for continuous low-altitude monitoring.',
        desc_ru: 'Стационарный анализ радиочастотного спектра, проверка предупреждений и регистрация событий для непрерывного мониторинга малых высот.',
        img: '/products/02-detection-monitoring/stationary-rf-detection-system.webp',
        mobileImg: '/products/02-detection-monitoring/stationary-rf-detection-system.webp',
        scale: 1.18,
        offsetY: 0,
        imagePadding: '30px',
        handle: 'stationary-rf-detection-system',
    },
    {
        top: 'Ku-Band Radar',
        top_ru: 'Радиолокационный контроль Ku-диапазона',
        main: 'Low-Altitude Early-Warning Radar',
        main_ru: 'Радиолокационная система раннего предупреждения',
        desc: 'Three-dimensional trajectory tracking for ultra-small RCS targets at low altitudes.',
        desc_ru: 'Трёхмерное сопровождение траекторий малоразмерных целей с низкой ЭПР на малых высотах.',
        img: '/products/02-detection-monitoring/low-altitude-detection-radar.webp',
        mobileImg: '/products/02-detection-monitoring/low-altitude-detection-radar.webp',
        scale: 1.12,
        offsetY: 0,
        imagePadding: '30px',
        handle: 'low-altitude-detection-radar-ku-band',
    },
    {
        top: 'EO/IR Verification',
        top_ru: 'Оптико-электронная верификация',
        main: 'Electro-Optical Tracking System',
        main_ru: 'Оптико-электронная система сопровождения',
        desc: 'Daylight and thermal imaging for visual confirmation, positioning review and continuous target observation.',
        desc_ru: 'Дневная и тепловизионная съёмка для визуального подтверждения, проверки координат и непрерывного наблюдения за целью.',
        img: '/products/02-detection-monitoring/electro-optical-tracking-system.webp',
        mobileImg: '/products/02-detection-monitoring/electro-optical-tracking-system.webp',
        scale: 1.12,
        offsetY: 0,
        imagePadding: '30px',
        handle: 'composite-electro-optical-tracking-system',
    },
    {
        top: 'Portable RF Analysis',
        top_ru: 'Переносной радиочастотный анализ',
        main: 'Portable RF Identification System',
        main_ru: 'Переносная система радиочастотной идентификации',
        desc: 'Field-ready spectrum analysis and event logging for patrol teams and temporary protection zones.',
        desc_ru: 'Полевой анализ спектра и регистрация событий для патрульных групп и временных зон защиты.',
        img: '/products/02-detection-monitoring/portable-rf-detection-case.webp',
        mobileImg: '/products/02-detection-monitoring/portable-rf-detection-case.webp',
        scale: 1.08,
        offsetY: 0,
        imagePadding: '30px',
        handle: 'portable-rf-detection-case',
    },
    {
        top: 'Integrated Field Monitoring',
        top_ru: 'Комплексный полевой мониторинг',
        main: 'Integrated RF Analysis Field Kit',
        main_ru: 'Комплексный полевой комплект радиочастотного анализа',
        desc: 'Portable multi-band monitoring, direction review and coordinated event records in a rugged field enclosure.',
        desc_ru: 'Переносной многодиапазонный мониторинг, оценка направления и единый журнал событий в защищённом полевом корпусе.',
        img: '/products/rf-systems/portable-integrated-rf-analysis-pro.webp',
        mobileImg: '/products/rf-systems/portable-integrated-rf-analysis-pro.webp',
        scale: 1.08,
        offsetY: 0,
        imagePadding: '30px',
        handle: 'portable-integrated-detection-event-logging-pro-low-altitude-monitoring',
    },
    {
        top: 'Perimeter Intelligence',
        top_ru: 'Интеллектуальный контроль периметра',
        main: 'Radar-Vision Sentinel',
        main_ru: 'Радарно-оптический пост наблюдения',
        desc: 'Combined radar and EO/IR observation for perimeter awareness, alert verification and long-range tracking.',
        desc_ru: 'Совмещённое радиолокационное и оптико-электронное наблюдение для контроля периметра, проверки тревог и дальнего сопровождения.',
        img: '/products/surveillance/FC-RDS500-4R-Radar-Vision-Sentinel.webp',
        mobileImg: '/products/surveillance/FC-RDS500-4R-Radar-Vision-Sentinel.webp',
        scale: 1.06,
        offsetY: 0,
        imagePadding: '26px',
        handle: 'fc-rds500-4r-radar-vision-sentinel',
    },
];

export const solutions = [
    {
        id: 'critical-infrastructure-airspace-monitoring',
        title: 'Critical Infrastructure Protection',
        title_ru: 'Защита критической инфраструктуры',
        img: '/solutions/defense-applications/defense_solution_center/01 Critical Infrastructure.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/01 Critical Infrastructure.webp',
        link: '/solutions/critical-infrastructure-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'power-plant-airspace-monitoring',
        title: 'Power Plant Protection',
        title_ru: 'Защита энергетических объектов',
        img: '/solutions/defense-applications/defense_solution_center/02 Power Plants.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/02 Power Plants.webp',
        link: '/solutions/power-plant-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'airport-security-protection',
        title: 'Airport Perimeter Protection',
        title_ru: 'Защита периметра аэропортов',
        img: '/solutions/defense-applications/defense_solution_center/03 Airports.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/03 Airports.webp',
        link: '/solutions/airport-security-protection',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'border-airspace-monitoring',
        title: 'Border Sector Monitoring',
        title_ru: 'Мониторинг приграничных участков',
        img: '/solutions/defense-applications/defense_solution_center/04 Borders.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/04 Borders.webp',
        link: '/solutions/border-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'public-safety-airspace-monitoring',
        title: 'Public-Site Protection',
        title_ru: 'Защита общественных объектов',
        img: '/solutions/defense-applications/defense_solution_center/05 Public Safety.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/05 Public Safety.webp',
        link: '/solutions/public-safety-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'correctional-facility-airspace-monitoring',
        title: 'Correctional Facility Protection',
        title_ru: 'Защита исправительных учреждений',
        img: '/solutions/defense-applications/defense_solution_center/06 Prisons.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/06 Prisons.webp',
        link: '/solutions/correctional-facility-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'port-airspace-monitoring',
        title: 'Port Perimeter Protection',
        title_ru: 'Защита портовых территорий',
        img: '/solutions/defense-applications/defense_solution_center/07 Ports.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/07 Ports.webp',
        link: '/solutions/port-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'mass-event-airspace-monitoring',
        title: 'Mass-Event Protection',
        title_ru: 'Защита массовых мероприятий',
        img: '/solutions/defense-applications/defense_solution_center/08 Mass Events.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/08 Mass Events.webp',
        link: '/solutions/mass-event-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'vip-private-property-airspace-monitoring',
        title: 'Private-Site Protection',
        title_ru: 'Защита частных объектов',
        img: '/solutions/defense-applications/defense_solution_center/09 VIPs & Private Property.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/09 VIPs & Private Property.webp',
        link: '/solutions/vip-private-property-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
    {
        id: 'enterprise-airspace-monitoring',
        title: 'Industrial Enterprise Protection',
        title_ru: 'Защита промышленных предприятий',
        img: '/solutions/defense-applications/defense_solution_center/10 Enterprises.webp',
        mobileImg: '/solutions/defense-applications/defense_solution_center/10 Enterprises.webp',
        link: '/solutions/enterprise-airspace-monitoring',
        objectPosition: '50% 50%',
        imageScale: 1,
    },
];

export const homeCases: never[] = [];
export const homepageSolutions = solutions;
