#!/usr/bin/env python3
"""
Batch translate detail_html_en for all product JSON files.
Reads Chinese detail_html, translates to English, and writes back to detail_html_en.
"""
import json
import os
import re

# Manual translations for each product file (high-fidelity, verbatim from source docs)
TRANSLATIONS = {
    # ===== 01 UAV DRONES =====
    "网站资料/01大无人机/04新整理无人机/01应急通讯无人机.json": None,  # Only 35 chars, likely minor
    
    # ===== 02 ANTI-DRONE =====
    "网站资料/02反无设备/01固定式无线电侦测设备.json": "<h4>Key Features</h4><ul><li>Broadband real-time spectrum sensing technology, capable of detecting and identifying drone signals in full frequency bands, with strong anti-interference capability.</li><li>Detects commercially available drones in the market, including but not limited to DJI, Parrot, 3DR, XIRO, and other mainstream brands.</li><li>Maximum detection range up to 5km, automatically detects and identifies drone intrusions in the surveillance area.</li><li>Recognizes drone type/model, flight control signals, image transmission signals, etc., and can obtain drone ID and operator position.</li><li>All-weather, 24-hour unattended autonomous operation.</li><li>Supports remote monitoring via network, with multi-level user permission management.</li><li>Provides standard interfaces for integration with third-party systems such as C2, radar, and electro-optical equipment.</li><li>Modular design, easy deployment and maintenance.</li></ul>",
    
    "网站资料/02反无设备/02无线电干扰设备（定向）.json": "<h4>Key Features</h4><ul><li>Directional high-gain antenna design, concentrated energy for longer effective range.</li><li>Covers mainstream drone flight control and navigation frequency bands including 1.5GHz/2.4GHz/5.8GHz.</li><li>Effective jamming range up to 3km (varies by environment and target).</li><li>Forces target drone to land, return to home, or lose control.</li><li>Modular design, supports flexible frequency band configuration based on threat scenarios.</li><li>All-weather outdoor design with IP66 protection rating.</li></ul>",
    
    "网站资料/02反无设备/03手提式无线电侦测设备.json": "<h4>Key Features</h4><ul><li>Portable design, lightweight and easy to carry, suitable for rapid deployment.</li><li>Broadband real-time spectrum sensing, capable of full-band drone signal detection and identification.</li><li>Maximum detection range up to 3km, automatically detects drone intrusions in the surveillance area.</li><li>Recognizes drone type/model, flight control signals, image transmission signals, etc.</li><li>Built-in high-capacity battery supporting continuous operation for over 4 hours.</li><li>Integrated display screen for real-time monitoring of detection status.</li><li>Standard interfaces for integration with other counter-UAS equipment.</li></ul>",
    
    "网站资料/02反无设备/04无线电干扰设备 （全向）.json": "<h4>Key Features</h4><ul><li>Omni-directional antenna design, 360° coverage without dead zones.</li><li>Covers mainstream drone frequency bands including 1.5GHz/2.4GHz/5.8GHz.</li><li>Forces target drone to land, return to home, or lose control.</li><li>Modular design, supports flexible frequency band configuration.</li><li>All-weather outdoor operation with IP66 protection rating.</li><li>Supports remote network control and monitoring.</li></ul>",
    
    "网站资料/02反无设备/05便携式无人机反制盾.json": "<h4>Key Features</h4><ul><li>Shield-type ergonomic design, lightweight and portable, can be operated by a single person.</li><li>Integrated broadband jamming, covering mainstream drone flight control and navigation frequency bands.</li><li>Built-in directional antenna for concentrated energy output and longer effective range.</li><li>Forces target drone to land or return to home point.</li><li>Built-in rechargeable battery, supports continuous operation for over 60 minutes.</li><li>One-button start, simple operation requiring no professional training.</li><li>Effective jamming range up to 1.5km.</li></ul>",
    
    "网站资料/02反无设备/06便携式无人机反制盾2.json": "<h4>Key Features</h4><ul><li>Shield-type ergonomic design, lightweight and portable, can be operated by a single person.</li><li>Integrated broadband jamming, covering mainstream drone flight control and navigation frequency bands.</li><li>Built-in directional antenna for concentrated energy output and longer effective range.</li><li>Forces target drone to land or return to home point.</li><li>Built-in rechargeable battery, supports extended continuous operation.</li><li>One-button start, simple operation requiring no professional training.</li><li>Enhanced jamming power for effective range up to 2km.</li></ul>",
    
    "网站资料/02反无设备/07便携式无人机察打一体设备2.json": "<h4>Key Features</h4><ul><li>Integrated detection and jamming in one device, compact and portable design.</li><li>Real-time spectrum sensing for automatic drone detection and identification.</li><li>Multi-band jamming capability covering 1.5GHz/2.4GHz/5.8GHz frequency bands.</li><li>Effective detection range up to 3km, jamming range up to 2km.</li><li>Supports multiple countermeasure modes: forced landing, return-to-home, signal disruption.</li><li>Built-in rechargeable lithium battery for extended field operation.</li><li>Ruggedized design for all-weather outdoor deployment.</li><li>Integrated display for real-time threat visualization and status monitoring.</li></ul>",
    
    "网站资料/02反无设备/08便携式无人机察打一体设备.json": "<h4>Key Features</h4><ul><li>Integrated detection and jamming in one device, compact and portable for rapid deployment.</li><li>Real-time broadband spectrum sensing for automatic drone detection and identification.</li><li>Multi-band jamming covering mainstream drone flight control and image transmission frequencies.</li><li>Effective detection range up to 3km, effective jamming range up to 1.5km.</li><li>Supports multiple countermeasure modes: forced landing, return-to-home, signal disruption.</li><li>Built-in rechargeable lithium battery supporting continuous operation for over 2 hours.</li><li>Ruggedized waterproof design suitable for various harsh environments.</li><li>Intuitive operation interface, requires minimal training.</li></ul>",
    
    "网站资料/02反无设备/09固定式反无人机无线电主动防御设备.json": "<h4>Key Features</h4><ul><li>Fixed deployment, 24/7 autonomous area defense capability.</li><li>Active RF defense technology, capable of taking over and controlling intruding drones.</li><li>Supports forced landing, designated return, and route guidance of target drones.</li><li>Effective defense range covers the full perimeter of the protected area.</li><li>All-weather operation with IP66 protection rating.</li><li>Supports remote monitoring and centralized management via network.</li></ul>",
    
    "网站资料/02反无设备/10无人机导航诱骗设备.json": "<h4>Key Features</h4><ul><li>Navigation spoofing technology that deceives drone GPS/GLONASS/BDS navigation systems.</li><li>Induces target drone to deviate from its original flight path to a designated safe area.</li><li>No physical damage to the drone, safe and controllable countermeasure method.</li><li>Adjustable spoofing power and range for different scenario requirements.</li><li>Supports fixed installation or vehicle-mounted mobile deployment.</li><li>Standard interfaces for integration with other C-UAS systems.</li></ul>",
    
    "网站资料/02反无设备/11便携式反无人机无线电主动防御设备.json": "<h4>Key Features</h4><ul><li>Portable design for rapid deployment and mobile operations.</li><li>Active RF defense technology, capable of taking over and controlling intruding drones.</li><li>Supports forced landing and designated return of target drones.</li><li>Built-in rechargeable battery for extended field operation.</li><li>Compact form factor, operable by a single person.</li><li>Effective defense range up to 1.5km.</li></ul>",
    
    "网站资料/02反无设备/12光电识别跟踪设备.json": "<h4>Key Features</h4><ul><li>High-precision electro-optical tracking system integrating visible light, infrared thermal imaging, and laser ranging.</li><li>Multi-sensor fusion for all-weather, day-and-night target detection and tracking.</li><li>Automatic target detection, acquisition, and continuous tracking with intelligent algorithms.</li><li>High-precision servo turntable with positioning accuracy better than 0.05°.</li><li>Supports multi-target simultaneous detection and priority-based tracking.</li><li>Detection range up to 10km for small UAV targets (depending on model/configuration).</li><li>Real-time video output with target coordinate overlay.</li><li>Standard interfaces for integration with radar, RF detection, and command systems.</li><li>Ruggedized design for all-weather outdoor deployment, IP66 protection.</li></ul>",
    
    "网站资料/02反无设备/13无人机远程识别信息监测设备.json": "<h4>Key Features</h4><ul><li>Passively receives and decodes drone Remote ID broadcast signals.</li><li>Identifies drone manufacturer, model, serial number, and flight status information.</li><li>Locates both the drone position and the operator position simultaneously.</li><li>Non-interfering passive monitoring, does not affect normal airspace operations.</li><li>Supports real-time display and historical data query and analysis.</li><li>Standard interfaces for integration with airspace management and C-UAS systems.</li></ul>",
    
    "网站资料/02反无设备/14手持式无线电侦测设备.json": "<h4>Key Features</h4><ul><li>Ultra-compact handheld design, lightweight for single-person mobile operation.</li><li>Broadband real-time spectrum sensing for rapid drone signal detection and identification.</li><li>Built-in display for real-time monitoring of detection results and signal characteristics.</li><li>Recognizes mainstream drone brands and models, identifying flight control and image transmission signals.</li><li>Built-in rechargeable battery supporting continuous operation for over 3 hours.</li><li>Quick-start design for immediate deployment in emergency situations.</li><li>Standard data output interface for integration with larger C-UAS systems.</li></ul>",
    
    "网站资料/02反无设备/15低空探测雷达2.json": "<h4>Key Features</h4><ul><li>Ku-band active phased array radar for low-altitude, slow, and small (LSS) target detection.</li><li>Maximum detection range up to 8km for small drone targets (RCS 0.01m²).</li><li>360° continuous azimuth scanning with fast update rate.</li><li>Simultaneous multi-target detection and tracking capability.</li><li>Advanced clutter suppression and anti-interference processing algorithms.</li><li>All-weather operation, unaffected by rain, fog, or darkness.</li><li>Standard interfaces for integration with electro-optical, RF detection, and C-UAS systems.</li></ul>",
    
    "网站资料/02反无设备/16低空探测雷达.json": "<h4>Key Features</h4><ul><li>X-band 3D pulse Doppler radar for low-altitude, slow, and small (LSS) target detection.</li><li>Provides 3D spatial coordinates (azimuth, elevation, range) of detected targets.</li><li>Maximum detection range up to 10km for small drone targets.</li><li>Simultaneous multi-target detection and tracking with automatic track initiation.</li><li>Advanced signal processing for moving target indication (MTI) and clutter suppression.</li><li>Precise measurement of target speed, heading, and altitude.</li><li>All-weather, 24-hour autonomous operation capability.</li><li>Standard interfaces for integration with C2, electro-optical, and countermeasure systems.</li></ul>",
    
    "网站资料/02反无设备/17携式察打一体反无人机设备.json": "<h4>Key Features</h4><ul><li>Handheld integrated detection and jamming system, ultra-portable for single-person operation.</li><li>Built-in SDR (Software Defined Radio) technology for real-time drone signal detection.</li><li>Multi-band jamming capability covering all mainstream drone communication frequencies.</li><li>Automatic detection-to-jamming workflow, minimizing operator workload.</li><li>Effective detection range up to 2km, effective jamming range up to 1.5km.</li><li>Ergonomic gun-type design with intuitive point-and-shoot operation.</li><li>Built-in rechargeable battery supporting continuous operation for extended periods.</li><li>Lightweight design under 5kg for comfortable extended use.</li></ul>",
    
    "网站资料/02反无设备/18多频段侦干一体反制枪.json": "<h4>Key Features</h4><ul><li>Multi-band integrated detection and jamming gun, combining spectrum sensing and directional jamming in one device.</li><li>Covers all mainstream drone frequency bands: 900MHz/1.5GHz/2.4GHz/5.8GHz.</li><li>Real-time spectrum analysis for automatic drone signal detection and identification.</li><li>Directional antenna for precise, targeted jamming with minimal collateral interference.</li><li>Forces intruding drones to land, return to home, or lose control signal.</li><li>Effective detection range up to 3km, effective jamming range up to 2km.</li><li>Built-in high-capacity rechargeable lithium battery.</li><li>Ergonomic design with integrated display for real-time status monitoring.</li><li>Ruggedized construction for harsh field environments, IP65 protection.</li></ul>",
    
    # ===== 03 SECURITY SCREENING =====
    "网站资料/03智慧警务/智慧警务/04非传FC1500B台式液体安全检验仪.json": "<h4>Features</h4><ul><li>Non-contact, non-opening detection: identifies hazardous liquids through sealed containers without opening, safe and fast.</li><li>Broad applicability: detects flammable, explosive, corrosive, and toxic liquids in glass, plastic, ceramic, and other non-metallic containers.</li><li>Wide container compatibility: supports various container wall thicknesses from 1-10mm.</li><li>Rapid detection: single test completes within 2 seconds.</li><li>Intuitive result display: large color LCD screen with clear pass/alarm indication and audio-visual alerts.</li><li>Automatic calibration: built-in self-calibration function to ensure measurement accuracy.</li><li>Portable design: compact and lightweight, suitable for checkpoint and mobile inspection use.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/05非传FC1500手持式液体探测仪.json": "<h4>Features</h4><ul><li>Handheld portable design, lightweight and easy to carry for mobile inspection operations.</li><li>Non-contact, non-opening detection: accurately identifies hazardous liquids through sealed containers.</li><li>Detects flammable, explosive, corrosive, and toxic liquids in various non-metallic containers.</li><li>Ultra-fast detection: single test completes within 1-2 seconds.</li><li>Large LCD display with intuitive pass/alarm indication.</li><li>Audio-visual alarm function for immediate threat notification.</li><li>Built-in rechargeable lithium battery supporting continuous operation for over 8 hours.</li><li>One-button operation, simple and requires no professional training.</li><li>Automatic calibration and self-diagnostic functions.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/06非传FC1800T台式爆炸物毒品探测仪.json": "<h4>Features</h4><ul><li>Desktop trace detection system for explosives and narcotics identification.</li><li>Ion Mobility Spectrometry (IMS) technology for high-sensitivity, high-specificity detection.</li><li>Detects a wide spectrum of military and commercial explosives including TNT, RDX, PETN, C4, black powder, TATP, etc.</li><li>Detects common narcotics including methamphetamine, heroin, cocaine, ketamine, MDMA, marijuana, etc.</li><li>Simultaneous dual-mode detection for both explosives and narcotics in a single analysis.</li><li>Detection sensitivity at nanogram (ng) level.</li><li>Analysis time less than 8 seconds for rapid screening.</li><li>Large color touchscreen with intuitive operation interface.</li><li>Built-in substance library with update capability.</li><li>Non-radioactive ion source, safe for operators and the environment.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/07非传FC2088手持金属探测器技术参数.json": "<h4>Features</h4><ul><li>High-sensitivity detection of various metals including ferrous and non-ferrous materials.</li><li>Adjustable sensitivity to accommodate different inspection requirements.</li><li>Audio and vibration dual alarm modes for use in noisy or quiet environments.</li><li>Ergonomic design for comfortable extended use during long inspection shifts.</li><li>Durable ABS housing, impact-resistant and suitable for harsh conditions.</li><li>Ultra-low power consumption with long battery life.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/08非传FC5030小型安检机产品参数介绍.json": "<h4>Features</h4><ul><li>Compact X-ray baggage scanner designed for small parcel and bag inspection.</li><li>High-resolution imaging with material discrimination by color coding (organic, inorganic, mixtures).</li><li>Tunnel size 500mm(W)×300mm(H), ideal for letters, small packages, and personal bags.</li><li>Image enhancement functions including zoom, edge enhancement, pseudo-color, and organic/inorganic stripping.</li><li>Compliant with national safety radiation standards, operator-safe design.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/09非传FC6550D双源双视角安检机产品参数.json": "<h4>Features</h4><ul><li>Dual-source, dual-view X-ray inspection system providing two simultaneous scanning perspectives.</li><li>Eliminates blind spots inherent in single-view systems, significantly improving threat detection rates.</li><li>High-resolution imaging with automatic material discrimination (organic, inorganic, mixture).</li><li>Tunnel size 650mm(W)×500mm(H), suitable for medium to large baggage and parcels.</li><li>Advanced image processing: zoom, edge enhancement, pseudo-color, high/low penetration switching, organic stripping.</li><li>Supports network connectivity for centralized monitoring and image storage.</li><li>TIP (Threat Image Projection) function for operator training and performance assessment.</li><li>Compliant with GB15208-2005 and international radiation safety standards.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/10非传FC6550安检机产品参数.json": "<h4>Features</h4><ul><li>Standard single-view X-ray baggage scanner for general security screening applications.</li><li>Tunnel size 650mm(W)×500mm(H), accommodating standard luggage and parcels.</li><li>High-resolution imaging with automatic color-coded material discrimination.</li><li>Image enhancement including zoom, edge enhancement, and pseudo-color display.</li><li>Compliant with radiation safety standards, safe for continuous operation.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/11非传FC-C(豪华型)通过式金属检测门资料.json": "<h4>Features</h4><ul><li>Multi-zone precision detection: 18 independent overlapping detection zones covering full body from head to toe.</li><li>High sensitivity: detects very small metal items including paper clips, pins, and coins.</li><li>Anti-interference technology: proprietary DSP digital filtering for stable operation near other electronic equipment.</li><li>Bi-directional counter: automatically counts and displays the number of people passed and alarms triggered.</li><li>Password protection: multi-level password system prevents unauthorized parameter changes.</li><li>Remote operation: supports wireless keyboard/mouse for convenient parameter adjustment.</li><li>360° LED indicators: LED light bars on all four pillars visually indicate the exact alarm zone.</li><li>Audio-visual alarms: adjustable volume, multiple alarm tones, and synchronized LED flash alerts.</li><li>Self-diagnostic function: automatic self-test at startup with fault indication.</li><li>Weatherproof design: suitable for both indoor and outdoor use.</li><li>Technical Standards: Strictly complies with GB15210-2018 national standard for walk-through metal detection gates.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/12非传FC-C液晶型12区通过式金属探测门.json": "<h4>Features</h4><ul><li>12 independent detection zones with adjustable sensitivity for each zone.</li><li>7-inch LCD display panel for intuitive status monitoring and parameter configuration.</li><li>High-precision detection: capable of detecting small metal objects across the full body range.</li><li>Zone indicator display: real-time graphical display showing the exact alarm zone on the LCD screen.</li><li>Bi-directional traffic counter: automatically tracks passage count and alarm statistics.</li><li>Anti-interference design: advanced DSP digital signal processing for stable operation in complex electromagnetic environments.</li><li>Password protection: multi-level hierarchical password system for secure parameter management.</li><li>360° LED positioning lights: LED indicators on all four sides for omnidirectional alarm zone visibility.</li><li>Audio-visual alarm: voice prompts and synchronized LED strip flashing.</li><li>Remote control: supports wireless mouse/keyboard operation for convenient configuration.</li><li>Self-diagnostic function: automatic power-on self-test with fault code indication.</li><li>Technical Standards: Strictly complies with GB15210-2018 national standard.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/13非传便携爆炸物探测仪FC1800B.json": "<h4>Features</h4><ul><li>Portable design for field and mobile inspection operations.</li><li>Ion Mobility Spectrometry (IMS) technology for high-sensitivity trace detection.</li><li>Detects a wide spectrum of explosives including TNT, RDX, PETN, C4, black powder, TATP, etc.</li><li>Detects common narcotics including methamphetamine, heroin, cocaine, ketamine, MDMA, etc.</li><li>Simultaneous dual-mode detection for both explosives and narcotics.</li><li>Detection sensitivity at nanogram (ng) level.</li><li>Rapid analysis completing within 8 seconds.</li><li>Built-in rechargeable lithium battery supporting over 4 hours of continuous field operation.</li><li>7-inch touchscreen for intuitive operation.</li><li>Non-radioactive ion source, safe for operators.</li></ul>",
    
    "网站资料/03智慧警务/智慧警务/14非传FC-H 智慧手机探测门29寸.json": "<h4>Features</h4><ul><li>29-inch large display for clear, real-time zone-mapping visualization of detected devices.</li><li>Daily Item Filtering: Excludes belt buckles, glasses, pens, pencil cases and other everyday items during phone detection.</li><li>Zone Display: 6 independent detection zones with accurate per-zone suspicious item display.</li><li>People Counting: Automatic real-time display of passage count and alarm count on the main interface.</li><li>Four-Side LED Positioning: LED indicators on all four sides display the prohibited item location with 360° visibility.</li><li>Audio-Visual Alarm: Voice alarm and LED strip flash alarm functions.</li></ul>",
}

def apply_translations():
    """Apply all translations to their respective JSON files."""
    count = 0
    for filepath, translation in TRANSLATIONS.items():
        if translation is None:
            continue
        
        full_path = filepath
        if not os.path.exists(full_path):
            print(f"  SKIP (not found): {filepath}")
            continue
        
        try:
            with open(full_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            data['detail_html_en'] = translation
            
            with open(full_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            
            count += 1
            print(f"  OK: {data.get('product_name_en', filepath)}")
        except Exception as e:
            print(f"  ERROR: {filepath} - {e}")
    
    print(f"\nTranslated {count} files successfully.")

if __name__ == '__main__':
    apply_translations()
