CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  handle TEXT UNIQUE NOT NULL,
  product_name_en TEXT NOT NULL,
  category_primary TEXT NOT NULL,
  summary_en TEXT,
  key_application_en TEXT,
  key_parameter_1_en TEXT,
  key_parameter_2_en TEXT,
  parameters_en TEXT,
  detail_html_en TEXT,
  product_name_ru TEXT,
  summary_ru TEXT,
  key_application_ru TEXT,
  key_parameter_1_ru TEXT,
  key_parameter_2_ru TEXT,
  parameters_ru TEXT,
  detail_html_ru TEXT,
  main_image TEXT,
  is_published INTEGER DEFAULT 1,
  raw_json TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS solutions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  handle TEXT UNIQUE NOT NULL,
  category_id TEXT NOT NULL,
  category_name TEXT NOT NULL,
  product_name_en TEXT NOT NULL,
  summary_en TEXT,
  key_application_en TEXT,
  parameters_en TEXT,
  detail_html_en TEXT,
  product_name_ru TEXT,
  summary_ru TEXT,
  key_application_ru TEXT,
  key_parameter_1_ru TEXT,
  key_parameter_2_ru TEXT,
  parameters_ru TEXT,
  detail_html_ru TEXT,
  main_image TEXT,
  recommended_products TEXT,
  is_published INTEGER DEFAULT 1,
  raw_json TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  handle TEXT UNIQUE NOT NULL,
  title_en TEXT NOT NULL,
  description_en TEXT,
  devices_en TEXT,
  parameters_en TEXT,
  title_ru TEXT,
  description_ru TEXT,
  devices_ru TEXT,
  parameters_ru TEXT,
  main_image TEXT,
  case_images TEXT,
  region_en TEXT,
  country_en TEXT,
  region_ru TEXT,
  country_ru TEXT,
  solution_category_id TEXT,
  recommended_product_handles TEXT,
  is_published INTEGER DEFAULT 1,
  raw_json TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  image TEXT,
  content TEXT,
  title_ru TEXT,
  content_ru TEXT,
  is_published INTEGER DEFAULT 1,
  raw_json TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT,
  email TEXT NOT NULL,
  contact_method TEXT,
  country_code TEXT,
  phone TEXT,
  demands TEXT,
  message TEXT,
  source_page TEXT,
  is_read INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_primary);
CREATE INDEX IF NOT EXISTS idx_products_handle ON products(handle);
CREATE INDEX IF NOT EXISTS idx_products_published ON products(is_published);
CREATE INDEX IF NOT EXISTS idx_solutions_category ON solutions(category_id);
CREATE INDEX IF NOT EXISTS idx_solutions_handle ON solutions(handle);
CREATE INDEX IF NOT EXISTS idx_solutions_published ON solutions(is_published);
CREATE INDEX IF NOT EXISTS idx_cases_solution_category ON cases(solution_category_id);
CREATE INDEX IF NOT EXISTS idx_cases_handle ON cases(handle);
CREATE INDEX IF NOT EXISTS idx_cases_published ON cases(is_published);
CREATE INDEX IF NOT EXISTS idx_media_category ON media(category);
CREATE INDEX IF NOT EXISTS idx_media_published ON media(is_published);
CREATE INDEX IF NOT EXISTS idx_inquiries_created_at ON inquiries(created_at DESC);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE solutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE media ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public reads published products" ON products;
CREATE POLICY "Public reads published products"
  ON products FOR SELECT
  TO anon, authenticated
  USING (COALESCE(is_published, 1) = 1);

DROP POLICY IF EXISTS "Public reads published solutions" ON solutions;
CREATE POLICY "Public reads published solutions"
  ON solutions FOR SELECT
  TO anon, authenticated
  USING (COALESCE(is_published, 1) = 1);

DROP POLICY IF EXISTS "Public reads published cases" ON cases;
CREATE POLICY "Public reads published cases"
  ON cases FOR SELECT
  TO anon, authenticated
  USING (COALESCE(is_published, 1) = 1);

DROP POLICY IF EXISTS "Public reads published media" ON media;
CREATE POLICY "Public reads published media"
  ON media FOR SELECT
  TO anon, authenticated
  USING (COALESCE(is_published, 1) = 1);

DROP POLICY IF EXISTS "Public reads non-sensitive site settings" ON site_settings;
CREATE POLICY "Public reads non-sensitive site settings"
  ON site_settings FOR SELECT
  TO anon, authenticated
  USING (key LIKE 'tracking.%' OR key LIKE 'chat.%');
